// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package vectorstoremocks

import (
	"context"
	"time"

	"github.com/serengeti-sh/meerkat/internal/vectorstore"
	mock "github.com/stretchr/testify/mock"
)

// NewVectorStoreMock creates a new instance of VectorStoreMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVectorStoreMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *VectorStoreMock {
	mock := &VectorStoreMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// VectorStoreMock is an autogenerated mock type for the VectorStore type
type VectorStoreMock struct {
	mock.Mock
}

type VectorStoreMock_Expecter struct {
	mock *mock.Mock
}

func (_m *VectorStoreMock) EXPECT() *VectorStoreMock_Expecter {
	return &VectorStoreMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type VectorStoreMock
func (_mock *VectorStoreMock) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VectorStoreMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type VectorStoreMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *VectorStoreMock_Expecter) Close() *VectorStoreMock_Close_Call {
	return &VectorStoreMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *VectorStoreMock_Close_Call) Run(run func()) *VectorStoreMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VectorStoreMock_Close_Call) Return(err error) *VectorStoreMock_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VectorStoreMock_Close_Call) RunAndReturn(run func() error) *VectorStoreMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type VectorStoreMock
func (_mock *VectorStoreMock) Insert(ctx context.Context, records []vectorstore.Record) error {
	ret := _mock.Called(ctx, records)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []vectorstore.Record) error); ok {
		r0 = returnFunc(ctx, records)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VectorStoreMock_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type VectorStoreMock_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - records []vectorstore.Record
func (_e *VectorStoreMock_Expecter) Insert(ctx interface{}, records interface{}) *VectorStoreMock_Insert_Call {
	return &VectorStoreMock_Insert_Call{Call: _e.mock.On("Insert", ctx, records)}
}

func (_c *VectorStoreMock_Insert_Call) Run(run func(ctx context.Context, records []vectorstore.Record)) *VectorStoreMock_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []vectorstore.Record
		if args[1] != nil {
			arg1 = args[1].([]vectorstore.Record)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VectorStoreMock_Insert_Call) Return(err error) *VectorStoreMock_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VectorStoreMock_Insert_Call) RunAndReturn(run func(ctx context.Context, records []vectorstore.Record) error) *VectorStoreMock_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type VectorStoreMock
func (_mock *VectorStoreMock) Search(ctx context.Context, vector []float32, limit int, timeRange time.Duration) ([]vectorstore.SearchResult, error) {
	ret := _mock.Called(ctx, vector, limit, timeRange)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []vectorstore.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []float32, int, time.Duration) ([]vectorstore.SearchResult, error)); ok {
		return returnFunc(ctx, vector, limit, timeRange)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []float32, int, time.Duration) []vectorstore.SearchResult); ok {
		r0 = returnFunc(ctx, vector, limit, timeRange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]vectorstore.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []float32, int, time.Duration) error); ok {
		r1 = returnFunc(ctx, vector, limit, timeRange)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VectorStoreMock_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type VectorStoreMock_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - vector []float32
//   - limit int
//   - timeRange time.Duration
func (_e *VectorStoreMock_Expecter) Search(ctx interface{}, vector interface{}, limit interface{}, timeRange interface{}) *VectorStoreMock_Search_Call {
	return &VectorStoreMock_Search_Call{Call: _e.mock.On("Search", ctx, vector, limit, timeRange)}
}

func (_c *VectorStoreMock_Search_Call) Run(run func(ctx context.Context, vector []float32, limit int, timeRange time.Duration)) *VectorStoreMock_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []float32
		if args[1] != nil {
			arg1 = args[1].([]float32)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *VectorStoreMock_Search_Call) Return(searchResults []vectorstore.SearchResult, err error) *VectorStoreMock_Search_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *VectorStoreMock_Search_Call) RunAndReturn(run func(ctx context.Context, vector []float32, limit int, timeRange time.Duration) ([]vectorstore.SearchResult, error)) *VectorStoreMock_Search_Call {
	_c.Call.Return(run)
	return _c
}
