// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package notifymocks

import (
	"context"

	"github.com/serengeti-sh/meerkat/internal/notify"
	mock "github.com/stretchr/testify/mock"
)

// NewServiceMock creates a new instance of ServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceMock is an autogenerated mock type for the Service type
type ServiceMock struct {
	mock.Mock
}

type ServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceMock) EXPECT() *ServiceMock_Expecter {
	return &ServiceMock_Expecter{mock: &_m.Mock}
}

// Report provides a mock function for the type ServiceMock
func (_mock *ServiceMock) Report(ctx context.Context, report *notify.ReportData) error {
	ret := _mock.Called(ctx, report)

	if len(ret) == 0 {
		panic("no return value specified for Report")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *notify.ReportData) error); ok {
		r0 = returnFunc(ctx, report)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ServiceMock_Report_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Report'
type ServiceMock_Report_Call struct {
	*mock.Call
}

// Report is a helper method to define mock.On call
//   - ctx context.Context
//   - report *notify.ReportData
func (_e *ServiceMock_Expecter) Report(ctx interface{}, report interface{}) *ServiceMock_Report_Call {
	return &ServiceMock_Report_Call{Call: _e.mock.On("Report", ctx, report)}
}

func (_c *ServiceMock_Report_Call) Run(run func(ctx context.Context, report *notify.ReportData)) *ServiceMock_Report_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *notify.ReportData
		if args[1] != nil {
			arg1 = args[1].(*notify.ReportData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceMock_Report_Call) Return(err error) *ServiceMock_Report_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ServiceMock_Report_Call) RunAndReturn(run func(ctx context.Context, report *notify.ReportData) error) *ServiceMock_Report_Call {
	_c.Call.Return(run)
	return _c
}
