// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package reportmocks

import (
	"context"
	"time"

	"github.com/serengeti-sh/meerkat/internal/report"
	mock "github.com/stretchr/testify/mock"
)

// NewRepositoryMock creates a new instance of RepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryMock {
	mock := &RepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RepositoryMock is an autogenerated mock type for the Repository type
type RepositoryMock struct {
	mock.Mock
}

type RepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryMock) EXPECT() *RepositoryMock_Expecter {
	return &RepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type RepositoryMock
func (_mock *RepositoryMock) Create(ctx context.Context, report1 *report.Report) error {
	ret := _mock.Called(ctx, report1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *report.Report) error); ok {
		r0 = returnFunc(ctx, report1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - report1 *report.Report
func (_e *RepositoryMock_Expecter) Create(ctx interface{}, report1 interface{}) *RepositoryMock_Create_Call {
	return &RepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, report1)}
}

func (_c *RepositoryMock_Create_Call) Run(run func(ctx context.Context, report1 *report.Report)) *RepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *report.Report
		if args[1] != nil {
			arg1 = args[1].(*report.Report)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepositoryMock_Create_Call) Return(err error) *RepositoryMock_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RepositoryMock_Create_Call) RunAndReturn(run func(ctx context.Context, report1 *report.Report) error) *RepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveByQuery provides a mock function for the type RepositoryMock
func (_mock *RepositoryMock) FindActiveByQuery(ctx context.Context, trigger string, query string, since time.Time) (*report.Report, error) {
	ret := _mock.Called(ctx, trigger, query, since)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByQuery")
	}

	var r0 *report.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*report.Report, error)); ok {
		return returnFunc(ctx, trigger, query, since)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *report.Report); ok {
		r0 = returnFunc(ctx, trigger, query, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*report.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = returnFunc(ctx, trigger, query, since)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryMock_FindActiveByQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByQuery'
type RepositoryMock_FindActiveByQuery_Call struct {
	*mock.Call
}

// FindActiveByQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - trigger string
//   - query string
//   - since time.Time
func (_e *RepositoryMock_Expecter) FindActiveByQuery(ctx interface{}, trigger interface{}, query interface{}, since interface{}) *RepositoryMock_FindActiveByQuery_Call {
	return &RepositoryMock_FindActiveByQuery_Call{Call: _e.mock.On("FindActiveByQuery", ctx, trigger, query, since)}
}

func (_c *RepositoryMock_FindActiveByQuery_Call) Run(run func(ctx context.Context, trigger string, query string, since time.Time)) *RepositoryMock_FindActiveByQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RepositoryMock_FindActiveByQuery_Call) Return(report1 *report.Report, err error) *RepositoryMock_FindActiveByQuery_Call {
	_c.Call.Return(report1, err)
	return _c
}

func (_c *RepositoryMock_FindActiveByQuery_Call) RunAndReturn(run func(ctx context.Context, trigger string, query string, since time.Time) (*report.Report, error)) *RepositoryMock_FindActiveByQuery_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type RepositoryMock
func (_mock *RepositoryMock) GetByID(ctx context.Context, id string) (*report.Report, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *report.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*report.Report, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *report.Report); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*report.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type RepositoryMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *RepositoryMock_Expecter) GetByID(ctx interface{}, id interface{}) *RepositoryMock_GetByID_Call {
	return &RepositoryMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *RepositoryMock_GetByID_Call) Run(run func(ctx context.Context, id string)) *RepositoryMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepositoryMock_GetByID_Call) Return(report1 *report.Report, err error) *RepositoryMock_GetByID_Call {
	_c.Call.Return(report1, err)
	return _c
}

func (_c *RepositoryMock_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*report.Report, error)) *RepositoryMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type RepositoryMock
func (_mock *RepositoryMock) List(ctx context.Context, limit int) ([]*report.Report, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*report.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*report.Report, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*report.Report); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*report.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type RepositoryMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *RepositoryMock_Expecter) List(ctx interface{}, limit interface{}) *RepositoryMock_List_Call {
	return &RepositoryMock_List_Call{Call: _e.mock.On("List", ctx, limit)}
}

func (_c *RepositoryMock_List_Call) Run(run func(ctx context.Context, limit int)) *RepositoryMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepositoryMock_List_Call) Return(reports []*report.Report, err error) *RepositoryMock_List_Call {
	_c.Call.Return(reports, err)
	return _c
}

func (_c *RepositoryMock_List_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]*report.Report, error)) *RepositoryMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type RepositoryMock
func (_mock *RepositoryMock) Update(ctx context.Context, report1 *report.Report) error {
	ret := _mock.Called(ctx, report1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *report.Report) error); ok {
		r0 = returnFunc(ctx, report1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type RepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - report1 *report.Report
func (_e *RepositoryMock_Expecter) Update(ctx interface{}, report1 interface{}) *RepositoryMock_Update_Call {
	return &RepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, report1)}
}

func (_c *RepositoryMock_Update_Call) Run(run func(ctx context.Context, report1 *report.Report)) *RepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *report.Report
		if args[1] != nil {
			arg1 = args[1].(*report.Report)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepositoryMock_Update_Call) Return(err error) *RepositoryMock_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RepositoryMock_Update_Call) RunAndReturn(run func(ctx context.Context, report1 *report.Report) error) *RepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}
