{{- if .Values.analyzer.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "meerkat.fullname" . }}
  labels:
    {{- include "meerkat.labels" . | nindent 4 }}
  {{- with .Values.analyzer.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- range .Values.analyzer.httpRoute.parentRefs }}
    - name: {{ .name }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
      {{- if .sectionName }}
      sectionName: {{ .sectionName }}
      {{- end }}
      {{- if .port }}
      port: {{ .port }}
      {{- end }}
    {{- end }}
  hostnames:
    {{- range .Values.analyzer.httpRoute.hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    {{- range .Values.analyzer.httpRoute.rules }}
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ include "meerkat.fullname" $ }}-analyzer
          port: {{ $.Values.analyzer.service.port }}
          weight: 1
      {{- with .filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
