{{- if or .Values.secrets.database.password .Values.secrets.analyzer.apiKey .Values.secrets.reporter.slackWebhookURL -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "meerkat.fullname" . }}
  labels:
    {{- include "meerkat.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-2"
type: Opaque
data:
  {{- if .Values.secrets.database.password }}
  database-password: {{ .Values.secrets.database.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.analyzer.apiKey }}
  analyzer-api-key: {{ .Values.secrets.analyzer.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.reporter.slackWebhookURL }}
  slack-webhook-url: {{ .Values.secrets.reporter.slackWebhookURL | b64enc | quote }}
  {{- end }}
{{- end }}
