// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ragmocks

import (
	"context"
	"time"

	"github.com/serengeti-sh/meerkat/internal/rag"
	mock "github.com/stretchr/testify/mock"
)

// NewServiceMock creates a new instance of ServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceMock is an autogenerated mock type for the Service type
type ServiceMock struct {
	mock.Mock
}

type ServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceMock) EXPECT() *ServiceMock_Expecter {
	return &ServiceMock_Expecter{mock: &_m.Mock}
}

// GetContext provides a mock function for the type ServiceMock
func (_mock *ServiceMock) GetContext(ctx context.Context, service string, start time.Time, end time.Time, limit int) ([]rag.SearchResult, error) {
	ret := _mock.Called(ctx, service, start, end, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 []rag.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, int) ([]rag.SearchResult, error)); ok {
		return returnFunc(ctx, service, start, end, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, int) []rag.SearchResult); ok {
		r0 = returnFunc(ctx, service, start, end, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rag.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time, int) error); ok {
		r1 = returnFunc(ctx, service, start, end, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type ServiceMock_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
//   - ctx context.Context
//   - service string
//   - start time.Time
//   - end time.Time
//   - limit int
func (_e *ServiceMock_Expecter) GetContext(ctx interface{}, service interface{}, start interface{}, end interface{}, limit interface{}) *ServiceMock_GetContext_Call {
	return &ServiceMock_GetContext_Call{Call: _e.mock.On("GetContext", ctx, service, start, end, limit)}
}

func (_c *ServiceMock_GetContext_Call) Run(run func(ctx context.Context, service string, start time.Time, end time.Time, limit int)) *ServiceMock_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ServiceMock_GetContext_Call) Return(searchResults []rag.SearchResult, err error) *ServiceMock_GetContext_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *ServiceMock_GetContext_Call) RunAndReturn(run func(ctx context.Context, service string, start time.Time, end time.Time, limit int) ([]rag.SearchResult, error)) *ServiceMock_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// Ingest provides a mock function for the type ServiceMock
func (_mock *ServiceMock) Ingest(ctx context.Context, entries []rag.LogEntry) (*rag.IngestResult, error) {
	ret := _mock.Called(ctx, entries)

	if len(ret) == 0 {
		panic("no return value specified for Ingest")
	}

	var r0 *rag.IngestResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []rag.LogEntry) (*rag.IngestResult, error)); ok {
		return returnFunc(ctx, entries)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []rag.LogEntry) *rag.IngestResult); ok {
		r0 = returnFunc(ctx, entries)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rag.IngestResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []rag.LogEntry) error); ok {
		r1 = returnFunc(ctx, entries)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_Ingest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ingest'
type ServiceMock_Ingest_Call struct {
	*mock.Call
}

// Ingest is a helper method to define mock.On call
//   - ctx context.Context
//   - entries []rag.LogEntry
func (_e *ServiceMock_Expecter) Ingest(ctx interface{}, entries interface{}) *ServiceMock_Ingest_Call {
	return &ServiceMock_Ingest_Call{Call: _e.mock.On("Ingest", ctx, entries)}
}

func (_c *ServiceMock_Ingest_Call) Run(run func(ctx context.Context, entries []rag.LogEntry)) *ServiceMock_Ingest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []rag.LogEntry
		if args[1] != nil {
			arg1 = args[1].([]rag.LogEntry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceMock_Ingest_Call) Return(ingestResult *rag.IngestResult, err error) *ServiceMock_Ingest_Call {
	_c.Call.Return(ingestResult, err)
	return _c
}

func (_c *ServiceMock_Ingest_Call) RunAndReturn(run func(ctx context.Context, entries []rag.LogEntry) (*rag.IngestResult, error)) *ServiceMock_Ingest_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type ServiceMock
func (_mock *ServiceMock) Search(ctx context.Context, query string, opts rag.SearchOptions) ([]rag.SearchResult, error) {
	ret := _mock.Called(ctx, query, opts)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []rag.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, rag.SearchOptions) ([]rag.SearchResult, error)); ok {
		return returnFunc(ctx, query, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, rag.SearchOptions) []rag.SearchResult); ok {
		r0 = returnFunc(ctx, query, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rag.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, rag.SearchOptions) error); ok {
		r1 = returnFunc(ctx, query, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type ServiceMock_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - opts rag.SearchOptions
func (_e *ServiceMock_Expecter) Search(ctx interface{}, query interface{}, opts interface{}) *ServiceMock_Search_Call {
	return &ServiceMock_Search_Call{Call: _e.mock.On("Search", ctx, query, opts)}
}

func (_c *ServiceMock_Search_Call) Run(run func(ctx context.Context, query string, opts rag.SearchOptions)) *ServiceMock_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 rag.SearchOptions
		if args[2] != nil {
			arg2 = args[2].(rag.SearchOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ServiceMock_Search_Call) Return(searchResults []rag.SearchResult, err error) *ServiceMock_Search_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *ServiceMock_Search_Call) RunAndReturn(run func(ctx context.Context, query string, opts rag.SearchOptions) ([]rag.SearchResult, error)) *ServiceMock_Search_Call {
	_c.Call.Return(run)
	return _c
}
