// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package inspectormocks

import (
	"context"

	"github.com/serengeti-sh/meerkat/internal/inspector"
	"github.com/serengeti-sh/meerkat/internal/report"
	mock "github.com/stretchr/testify/mock"
)

// NewServiceMock creates a new instance of ServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceMock is an autogenerated mock type for the Service type
type ServiceMock struct {
	mock.Mock
}

type ServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceMock) EXPECT() *ServiceMock_Expecter {
	return &ServiceMock_Expecter{mock: &_m.Mock}
}

// GetReport provides a mock function for the type ServiceMock
func (_mock *ServiceMock) GetReport(ctx context.Context, id string) (*report.Report, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetReport")
	}

	var r0 *report.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*report.Report, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *report.Report); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*report.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_GetReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReport'
type ServiceMock_GetReport_Call struct {
	*mock.Call
}

// GetReport is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ServiceMock_Expecter) GetReport(ctx interface{}, id interface{}) *ServiceMock_GetReport_Call {
	return &ServiceMock_GetReport_Call{Call: _e.mock.On("GetReport", ctx, id)}
}

func (_c *ServiceMock_GetReport_Call) Run(run func(ctx context.Context, id string)) *ServiceMock_GetReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceMock_GetReport_Call) Return(report1 *report.Report, err error) *ServiceMock_GetReport_Call {
	_c.Call.Return(report1, err)
	return _c
}

func (_c *ServiceMock_GetReport_Call) RunAndReturn(run func(ctx context.Context, id string) (*report.Report, error)) *ServiceMock_GetReport_Call {
	_c.Call.Return(run)
	return _c
}

// Inspect provides a mock function for the type ServiceMock
func (_mock *ServiceMock) Inspect(ctx context.Context, req inspector.InspectRequest) (*report.Report, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Inspect")
	}

	var r0 *report.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inspector.InspectRequest) (*report.Report, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inspector.InspectRequest) *report.Report); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*report.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inspector.InspectRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_Inspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Inspect'
type ServiceMock_Inspect_Call struct {
	*mock.Call
}

// Inspect is a helper method to define mock.On call
//   - ctx context.Context
//   - req inspector.InspectRequest
func (_e *ServiceMock_Expecter) Inspect(ctx interface{}, req interface{}) *ServiceMock_Inspect_Call {
	return &ServiceMock_Inspect_Call{Call: _e.mock.On("Inspect", ctx, req)}
}

func (_c *ServiceMock_Inspect_Call) Run(run func(ctx context.Context, req inspector.InspectRequest)) *ServiceMock_Inspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inspector.InspectRequest
		if args[1] != nil {
			arg1 = args[1].(inspector.InspectRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceMock_Inspect_Call) Return(report1 *report.Report, err error) *ServiceMock_Inspect_Call {
	_c.Call.Return(report1, err)
	return _c
}

func (_c *ServiceMock_Inspect_Call) RunAndReturn(run func(ctx context.Context, req inspector.InspectRequest) (*report.Report, error)) *ServiceMock_Inspect_Call {
	_c.Call.Return(run)
	return _c
}

// InspectByWebhook provides a mock function for the type ServiceMock
func (_mock *ServiceMock) InspectByWebhook(ctx context.Context, payload inspector.WebhookPayload) (*report.Report, error) {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for InspectByWebhook")
	}

	var r0 *report.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inspector.WebhookPayload) (*report.Report, error)); ok {
		return returnFunc(ctx, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inspector.WebhookPayload) *report.Report); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*report.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inspector.WebhookPayload) error); ok {
		r1 = returnFunc(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_InspectByWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InspectByWebhook'
type ServiceMock_InspectByWebhook_Call struct {
	*mock.Call
}

// InspectByWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - payload inspector.WebhookPayload
func (_e *ServiceMock_Expecter) InspectByWebhook(ctx interface{}, payload interface{}) *ServiceMock_InspectByWebhook_Call {
	return &ServiceMock_InspectByWebhook_Call{Call: _e.mock.On("InspectByWebhook", ctx, payload)}
}

func (_c *ServiceMock_InspectByWebhook_Call) Run(run func(ctx context.Context, payload inspector.WebhookPayload)) *ServiceMock_InspectByWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inspector.WebhookPayload
		if args[1] != nil {
			arg1 = args[1].(inspector.WebhookPayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceMock_InspectByWebhook_Call) Return(report1 *report.Report, err error) *ServiceMock_InspectByWebhook_Call {
	_c.Call.Return(report1, err)
	return _c
}

func (_c *ServiceMock_InspectByWebhook_Call) RunAndReturn(run func(ctx context.Context, payload inspector.WebhookPayload) (*report.Report, error)) *ServiceMock_InspectByWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// ListReports provides a mock function for the type ServiceMock
func (_mock *ServiceMock) ListReports(ctx context.Context, limit int) ([]*report.Report, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListReports")
	}

	var r0 []*report.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*report.Report, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*report.Report); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*report.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_ListReports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReports'
type ServiceMock_ListReports_Call struct {
	*mock.Call
}

// ListReports is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *ServiceMock_Expecter) ListReports(ctx interface{}, limit interface{}) *ServiceMock_ListReports_Call {
	return &ServiceMock_ListReports_Call{Call: _e.mock.On("ListReports", ctx, limit)}
}

func (_c *ServiceMock_ListReports_Call) Run(run func(ctx context.Context, limit int)) *ServiceMock_ListReports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceMock_ListReports_Call) Return(reports []*report.Report, err error) *ServiceMock_ListReports_Call {
	_c.Call.Return(reports, err)
	return _c
}

func (_c *ServiceMock_ListReports_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]*report.Report, error)) *ServiceMock_ListReports_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type ServiceMock
func (_mock *ServiceMock) Stop() {
	_mock.Called()
	return
}

// ServiceMock_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type ServiceMock_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *ServiceMock_Expecter) Stop() *ServiceMock_Stop_Call {
	return &ServiceMock_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *ServiceMock_Stop_Call) Run(run func()) *ServiceMock_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceMock_Stop_Call) Return() *ServiceMock_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceMock_Stop_Call) RunAndReturn(run func()) *ServiceMock_Stop_Call {
	_c.Run(run)
	return _c
}
