// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package inspectormocks

import (
	"context"

	"github.com/serengeti-sh/meerkat/internal/apperrors"
	"github.com/serengeti-sh/meerkat/internal/inspector"
	mock "github.com/stretchr/testify/mock"
)

// NewInspectorServiceMock creates a new instance of InspectorServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInspectorServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *InspectorServiceMock {
	mock := &InspectorServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InspectorServiceMock is an autogenerated mock type for the InspectorService type
type InspectorServiceMock struct {
	mock.Mock
}

type InspectorServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *InspectorServiceMock) EXPECT() *InspectorServiceMock_Expecter {
	return &InspectorServiceMock_Expecter{mock: &_m.Mock}
}

// GetReport provides a mock function for the type InspectorServiceMock
func (_mock *InspectorServiceMock) GetReport(ctx context.Context, id string) (*inspector.Report, apperrors.Error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetReport")
	}

	var r0 *inspector.Report
	var r1 apperrors.Error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*inspector.Report, apperrors.Error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *inspector.Report); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inspector.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) apperrors.Error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.Error)
		}
	}
	return r0, r1
}

// InspectorServiceMock_GetReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReport'
type InspectorServiceMock_GetReport_Call struct {
	*mock.Call
}

// GetReport is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *InspectorServiceMock_Expecter) GetReport(ctx interface{}, id interface{}) *InspectorServiceMock_GetReport_Call {
	return &InspectorServiceMock_GetReport_Call{Call: _e.mock.On("GetReport", ctx, id)}
}

func (_c *InspectorServiceMock_GetReport_Call) Run(run func(ctx context.Context, id string)) *InspectorServiceMock_GetReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InspectorServiceMock_GetReport_Call) Return(report *inspector.Report, error apperrors.Error) *InspectorServiceMock_GetReport_Call {
	_c.Call.Return(report, error)
	return _c
}

func (_c *InspectorServiceMock_GetReport_Call) RunAndReturn(run func(ctx context.Context, id string) (*inspector.Report, apperrors.Error)) *InspectorServiceMock_GetReport_Call {
	_c.Call.Return(run)
	return _c
}

// Inspect provides a mock function for the type InspectorServiceMock
func (_mock *InspectorServiceMock) Inspect(ctx context.Context, req inspector.InspectRequest) (*inspector.Report, apperrors.Error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Inspect")
	}

	var r0 *inspector.Report
	var r1 apperrors.Error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inspector.InspectRequest) (*inspector.Report, apperrors.Error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inspector.InspectRequest) *inspector.Report); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inspector.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inspector.InspectRequest) apperrors.Error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.Error)
		}
	}
	return r0, r1
}

// InspectorServiceMock_Inspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Inspect'
type InspectorServiceMock_Inspect_Call struct {
	*mock.Call
}

// Inspect is a helper method to define mock.On call
//   - ctx context.Context
//   - req inspector.InspectRequest
func (_e *InspectorServiceMock_Expecter) Inspect(ctx interface{}, req interface{}) *InspectorServiceMock_Inspect_Call {
	return &InspectorServiceMock_Inspect_Call{Call: _e.mock.On("Inspect", ctx, req)}
}

func (_c *InspectorServiceMock_Inspect_Call) Run(run func(ctx context.Context, req inspector.InspectRequest)) *InspectorServiceMock_Inspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inspector.InspectRequest
		if args[1] != nil {
			arg1 = args[1].(inspector.InspectRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InspectorServiceMock_Inspect_Call) Return(report *inspector.Report, error apperrors.Error) *InspectorServiceMock_Inspect_Call {
	_c.Call.Return(report, error)
	return _c
}

func (_c *InspectorServiceMock_Inspect_Call) RunAndReturn(run func(ctx context.Context, req inspector.InspectRequest) (*inspector.Report, apperrors.Error)) *InspectorServiceMock_Inspect_Call {
	_c.Call.Return(run)
	return _c
}

// InspectByWebhook provides a mock function for the type InspectorServiceMock
func (_mock *InspectorServiceMock) InspectByWebhook(ctx context.Context, payload inspector.WebhookPayload) (*inspector.Report, apperrors.Error) {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for InspectByWebhook")
	}

	var r0 *inspector.Report
	var r1 apperrors.Error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inspector.WebhookPayload) (*inspector.Report, apperrors.Error)); ok {
		return returnFunc(ctx, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inspector.WebhookPayload) *inspector.Report); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inspector.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inspector.WebhookPayload) apperrors.Error); ok {
		r1 = returnFunc(ctx, payload)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.Error)
		}
	}
	return r0, r1
}

// InspectorServiceMock_InspectByWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InspectByWebhook'
type InspectorServiceMock_InspectByWebhook_Call struct {
	*mock.Call
}

// InspectByWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - payload inspector.WebhookPayload
func (_e *InspectorServiceMock_Expecter) InspectByWebhook(ctx interface{}, payload interface{}) *InspectorServiceMock_InspectByWebhook_Call {
	return &InspectorServiceMock_InspectByWebhook_Call{Call: _e.mock.On("InspectByWebhook", ctx, payload)}
}

func (_c *InspectorServiceMock_InspectByWebhook_Call) Run(run func(ctx context.Context, payload inspector.WebhookPayload)) *InspectorServiceMock_InspectByWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inspector.WebhookPayload
		if args[1] != nil {
			arg1 = args[1].(inspector.WebhookPayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InspectorServiceMock_InspectByWebhook_Call) Return(report *inspector.Report, error apperrors.Error) *InspectorServiceMock_InspectByWebhook_Call {
	_c.Call.Return(report, error)
	return _c
}

func (_c *InspectorServiceMock_InspectByWebhook_Call) RunAndReturn(run func(ctx context.Context, payload inspector.WebhookPayload) (*inspector.Report, apperrors.Error)) *InspectorServiceMock_InspectByWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// ListReports provides a mock function for the type InspectorServiceMock
func (_mock *InspectorServiceMock) ListReports(ctx context.Context, limit int) ([]*inspector.Report, apperrors.Error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListReports")
	}

	var r0 []*inspector.Report
	var r1 apperrors.Error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*inspector.Report, apperrors.Error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*inspector.Report); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*inspector.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) apperrors.Error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.Error)
		}
	}
	return r0, r1
}

// InspectorServiceMock_ListReports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReports'
type InspectorServiceMock_ListReports_Call struct {
	*mock.Call
}

// ListReports is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *InspectorServiceMock_Expecter) ListReports(ctx interface{}, limit interface{}) *InspectorServiceMock_ListReports_Call {
	return &InspectorServiceMock_ListReports_Call{Call: _e.mock.On("ListReports", ctx, limit)}
}

func (_c *InspectorServiceMock_ListReports_Call) Run(run func(ctx context.Context, limit int)) *InspectorServiceMock_ListReports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InspectorServiceMock_ListReports_Call) Return(reports []*inspector.Report, error apperrors.Error) *InspectorServiceMock_ListReports_Call {
	_c.Call.Return(reports, error)
	return _c
}

func (_c *InspectorServiceMock_ListReports_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]*inspector.Report, apperrors.Error)) *InspectorServiceMock_ListReports_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type InspectorServiceMock
func (_mock *InspectorServiceMock) Stop() {
	_mock.Called()
	return
}

// InspectorServiceMock_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type InspectorServiceMock_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *InspectorServiceMock_Expecter) Stop() *InspectorServiceMock_Stop_Call {
	return &InspectorServiceMock_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *InspectorServiceMock_Stop_Call) Run(run func()) *InspectorServiceMock_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InspectorServiceMock_Stop_Call) Return() *InspectorServiceMock_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *InspectorServiceMock_Stop_Call) RunAndReturn(run func()) *InspectorServiceMock_Stop_Call {
	_c.Run(run)
	return _c
}
