// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/jx"

	std "encoding/json"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestCreateInspectReq_EncodeDecode(t *testing.T) {
	var typ CreateInspectReq
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CreateInspectReq
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestError_EncodeDecode(t *testing.T) {
	var typ Error
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 Error
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestGetHealthOK_EncodeDecode(t *testing.T) {
	var typ GetHealthOK
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 GetHealthOK
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestReceiveWebhookReq_EncodeDecode(t *testing.T) {
	var typ ReceiveWebhookReq
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ReceiveWebhookReq
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestReceiveWebhookReqData_EncodeDecode(t *testing.T) {
	var typ ReceiveWebhookReqData
	typ = make(ReceiveWebhookReqData)
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ReceiveWebhookReqData
	typ2 = make(ReceiveWebhookReqData)
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestReportResponse_EncodeDecode(t *testing.T) {
	var typ ReportResponse
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ReportResponse
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestReportResponseSeverity_EncodeDecode(t *testing.T) {
	var typ ReportResponseSeverity
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ReportResponseSeverity
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestReportResponseStatus_EncodeDecode(t *testing.T) {
	var typ ReportResponseStatus
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ReportResponseStatus
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestReportResponseTrigger_EncodeDecode(t *testing.T) {
	var typ ReportResponseTrigger
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ReportResponseTrigger
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
