// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateDatasourceOperation OperationName = "CreateDatasource"
	CreateInspectOperation    OperationName = "CreateInspect"
	GetHealthOperation        OperationName = "GetHealth"
	GetReportOperation        OperationName = "GetReport"
	ListDatasourcesOperation  OperationName = "ListDatasources"
	ListReportsOperation      OperationName = "ListReports"
	ReceiveWebhookOperation   OperationName = "ReceiveWebhook"
	TestDatasourceOperation   OperationName = "TestDatasource"
)
