// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

// Ref: #/components/schemas/CreateDatasourceRequest
type CreateDatasourceRequest struct {
	Name string                      `json:"name"`
	Type CreateDatasourceRequestType `json:"type"`
	URL  string                      `json:"url"`
}

// GetName returns the value of Name.
func (s *CreateDatasourceRequest) GetName() string {
	return s.Name
}

// GetType returns the value of Type.
func (s *CreateDatasourceRequest) GetType() CreateDatasourceRequestType {
	return s.Type
}

// GetURL returns the value of URL.
func (s *CreateDatasourceRequest) GetURL() string {
	return s.URL
}

// SetName sets the value of Name.
func (s *CreateDatasourceRequest) SetName(val string) {
	s.Name = val
}

// SetType sets the value of Type.
func (s *CreateDatasourceRequest) SetType(val CreateDatasourceRequestType) {
	s.Type = val
}

// SetURL sets the value of URL.
func (s *CreateDatasourceRequest) SetURL(val string) {
	s.URL = val
}

type CreateDatasourceRequestType string

const (
	CreateDatasourceRequestTypePrometheus   CreateDatasourceRequestType = "prometheus"
	CreateDatasourceRequestTypeVictoriaLogs CreateDatasourceRequestType = "victoria-logs"
	CreateDatasourceRequestTypeLoki         CreateDatasourceRequestType = "loki"
)

// AllValues returns all CreateDatasourceRequestType values.
func (CreateDatasourceRequestType) AllValues() []CreateDatasourceRequestType {
	return []CreateDatasourceRequestType{
		CreateDatasourceRequestTypePrometheus,
		CreateDatasourceRequestTypeVictoriaLogs,
		CreateDatasourceRequestTypeLoki,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateDatasourceRequestType) MarshalText() ([]byte, error) {
	switch s {
	case CreateDatasourceRequestTypePrometheus:
		return []byte(s), nil
	case CreateDatasourceRequestTypeVictoriaLogs:
		return []byte(s), nil
	case CreateDatasourceRequestTypeLoki:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateDatasourceRequestType) UnmarshalText(data []byte) error {
	switch CreateDatasourceRequestType(data) {
	case CreateDatasourceRequestTypePrometheus:
		*s = CreateDatasourceRequestTypePrometheus
		return nil
	case CreateDatasourceRequestTypeVictoriaLogs:
		*s = CreateDatasourceRequestTypeVictoriaLogs
		return nil
	case CreateDatasourceRequestTypeLoki:
		*s = CreateDatasourceRequestTypeLoki
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateInspectReq struct {
	Query       OptString `json:"query"`
	MetricQuery OptString `json:"metric_query"`
	LogQuery    OptString `json:"log_query"`
}

// GetQuery returns the value of Query.
func (s *CreateInspectReq) GetQuery() OptString {
	return s.Query
}

// GetMetricQuery returns the value of MetricQuery.
func (s *CreateInspectReq) GetMetricQuery() OptString {
	return s.MetricQuery
}

// GetLogQuery returns the value of LogQuery.
func (s *CreateInspectReq) GetLogQuery() OptString {
	return s.LogQuery
}

// SetQuery sets the value of Query.
func (s *CreateInspectReq) SetQuery(val OptString) {
	s.Query = val
}

// SetMetricQuery sets the value of MetricQuery.
func (s *CreateInspectReq) SetMetricQuery(val OptString) {
	s.MetricQuery = val
}

// SetLogQuery sets the value of LogQuery.
func (s *CreateInspectReq) SetLogQuery(val OptString) {
	s.LogQuery = val
}

// Ref: #/components/schemas/DatasourceResponse
type DatasourceResponse struct {
	ID        string                 `json:"id"`
	Name      string                 `json:"name"`
	Type      DatasourceResponseType `json:"type"`
	URL       string                 `json:"url"`
	CreatedAt OptDateTime            `json:"created_at"`
}

// GetID returns the value of ID.
func (s *DatasourceResponse) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *DatasourceResponse) GetName() string {
	return s.Name
}

// GetType returns the value of Type.
func (s *DatasourceResponse) GetType() DatasourceResponseType {
	return s.Type
}

// GetURL returns the value of URL.
func (s *DatasourceResponse) GetURL() string {
	return s.URL
}

// GetCreatedAt returns the value of CreatedAt.
func (s *DatasourceResponse) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *DatasourceResponse) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *DatasourceResponse) SetName(val string) {
	s.Name = val
}

// SetType sets the value of Type.
func (s *DatasourceResponse) SetType(val DatasourceResponseType) {
	s.Type = val
}

// SetURL sets the value of URL.
func (s *DatasourceResponse) SetURL(val string) {
	s.URL = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *DatasourceResponse) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

func (*DatasourceResponse) createDatasourceRes() {}

type DatasourceResponseType string

const (
	DatasourceResponseTypePrometheus   DatasourceResponseType = "prometheus"
	DatasourceResponseTypeVictoriaLogs DatasourceResponseType = "victoria-logs"
	DatasourceResponseTypeLoki         DatasourceResponseType = "loki"
)

// AllValues returns all DatasourceResponseType values.
func (DatasourceResponseType) AllValues() []DatasourceResponseType {
	return []DatasourceResponseType{
		DatasourceResponseTypePrometheus,
		DatasourceResponseTypeVictoriaLogs,
		DatasourceResponseTypeLoki,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s DatasourceResponseType) MarshalText() ([]byte, error) {
	switch s {
	case DatasourceResponseTypePrometheus:
		return []byte(s), nil
	case DatasourceResponseTypeVictoriaLogs:
		return []byte(s), nil
	case DatasourceResponseTypeLoki:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *DatasourceResponseType) UnmarshalText(data []byte) error {
	switch DatasourceResponseType(data) {
	case DatasourceResponseTypePrometheus:
		*s = DatasourceResponseTypePrometheus
		return nil
	case DatasourceResponseTypeVictoriaLogs:
		*s = DatasourceResponseTypeVictoriaLogs
		return nil
	case DatasourceResponseTypeLoki:
		*s = DatasourceResponseTypeLoki
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

// ErrorResponseStatusCode wraps ErrorResponse with StatusCode.
type ErrorResponseStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorResponseStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorResponseStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

func (*ErrorResponseStatusCode) createDatasourceRes() {}
func (*ErrorResponseStatusCode) createInspectRes()    {}
func (*ErrorResponseStatusCode) getReportRes()        {}
func (*ErrorResponseStatusCode) receiveWebhookRes()   {}
func (*ErrorResponseStatusCode) testDatasourceRes()   {}

type GetHealthOK struct {
	Status string `json:"status"`
}

// GetStatus returns the value of Status.
func (s *GetHealthOK) GetStatus() string {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *GetHealthOK) SetStatus(val string) {
	s.Status = val
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptReceiveWebhookReqData returns new OptReceiveWebhookReqData with value set to v.
func NewOptReceiveWebhookReqData(v ReceiveWebhookReqData) OptReceiveWebhookReqData {
	return OptReceiveWebhookReqData{
		Value: v,
		Set:   true,
	}
}

// OptReceiveWebhookReqData is optional ReceiveWebhookReqData.
type OptReceiveWebhookReqData struct {
	Value ReceiveWebhookReqData
	Set   bool
}

// IsSet returns true if OptReceiveWebhookReqData was set.
func (o OptReceiveWebhookReqData) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptReceiveWebhookReqData) Reset() {
	var v ReceiveWebhookReqData
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptReceiveWebhookReqData) SetTo(v ReceiveWebhookReqData) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptReceiveWebhookReqData) Get() (v ReceiveWebhookReqData, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptReceiveWebhookReqData) Or(d ReceiveWebhookReqData) ReceiveWebhookReqData {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptReportResponseSeverity returns new OptReportResponseSeverity with value set to v.
func NewOptReportResponseSeverity(v ReportResponseSeverity) OptReportResponseSeverity {
	return OptReportResponseSeverity{
		Value: v,
		Set:   true,
	}
}

// OptReportResponseSeverity is optional ReportResponseSeverity.
type OptReportResponseSeverity struct {
	Value ReportResponseSeverity
	Set   bool
}

// IsSet returns true if OptReportResponseSeverity was set.
func (o OptReportResponseSeverity) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptReportResponseSeverity) Reset() {
	var v ReportResponseSeverity
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptReportResponseSeverity) SetTo(v ReportResponseSeverity) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptReportResponseSeverity) Get() (v ReportResponseSeverity, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptReportResponseSeverity) Or(d ReportResponseSeverity) ReportResponseSeverity {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type ReceiveWebhookReq struct {
	Source  OptString                `json:"source"`
	Alert   OptString                `json:"alert"`
	Message OptString                `json:"message"`
	Data    OptReceiveWebhookReqData `json:"data"`
}

// GetSource returns the value of Source.
func (s *ReceiveWebhookReq) GetSource() OptString {
	return s.Source
}

// GetAlert returns the value of Alert.
func (s *ReceiveWebhookReq) GetAlert() OptString {
	return s.Alert
}

// GetMessage returns the value of Message.
func (s *ReceiveWebhookReq) GetMessage() OptString {
	return s.Message
}

// GetData returns the value of Data.
func (s *ReceiveWebhookReq) GetData() OptReceiveWebhookReqData {
	return s.Data
}

// SetSource sets the value of Source.
func (s *ReceiveWebhookReq) SetSource(val OptString) {
	s.Source = val
}

// SetAlert sets the value of Alert.
func (s *ReceiveWebhookReq) SetAlert(val OptString) {
	s.Alert = val
}

// SetMessage sets the value of Message.
func (s *ReceiveWebhookReq) SetMessage(val OptString) {
	s.Message = val
}

// SetData sets the value of Data.
func (s *ReceiveWebhookReq) SetData(val OptReceiveWebhookReqData) {
	s.Data = val
}

type ReceiveWebhookReqData map[string]jx.Raw

func (s *ReceiveWebhookReqData) init() ReceiveWebhookReqData {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/ReportResponse
type ReportResponse struct {
	ID          string                    `json:"id"`
	Trigger     ReportResponseTrigger     `json:"trigger"`
	TriggerID   string                    `json:"trigger_id"`
	Status      ReportResponseStatus      `json:"status"`
	Severity    OptReportResponseSeverity `json:"severity"`
	Summary     OptString                 `json:"summary"`
	Detail      OptString                 `json:"detail"`
	Datasources []string                  `json:"datasources"`
	Iterations  OptInt                    `json:"iterations"`
	CreatedAt   OptDateTime               `json:"created_at"`
}

// GetID returns the value of ID.
func (s *ReportResponse) GetID() string {
	return s.ID
}

// GetTrigger returns the value of Trigger.
func (s *ReportResponse) GetTrigger() ReportResponseTrigger {
	return s.Trigger
}

// GetTriggerID returns the value of TriggerID.
func (s *ReportResponse) GetTriggerID() string {
	return s.TriggerID
}

// GetStatus returns the value of Status.
func (s *ReportResponse) GetStatus() ReportResponseStatus {
	return s.Status
}

// GetSeverity returns the value of Severity.
func (s *ReportResponse) GetSeverity() OptReportResponseSeverity {
	return s.Severity
}

// GetSummary returns the value of Summary.
func (s *ReportResponse) GetSummary() OptString {
	return s.Summary
}

// GetDetail returns the value of Detail.
func (s *ReportResponse) GetDetail() OptString {
	return s.Detail
}

// GetDatasources returns the value of Datasources.
func (s *ReportResponse) GetDatasources() []string {
	return s.Datasources
}

// GetIterations returns the value of Iterations.
func (s *ReportResponse) GetIterations() OptInt {
	return s.Iterations
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ReportResponse) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *ReportResponse) SetID(val string) {
	s.ID = val
}

// SetTrigger sets the value of Trigger.
func (s *ReportResponse) SetTrigger(val ReportResponseTrigger) {
	s.Trigger = val
}

// SetTriggerID sets the value of TriggerID.
func (s *ReportResponse) SetTriggerID(val string) {
	s.TriggerID = val
}

// SetStatus sets the value of Status.
func (s *ReportResponse) SetStatus(val ReportResponseStatus) {
	s.Status = val
}

// SetSeverity sets the value of Severity.
func (s *ReportResponse) SetSeverity(val OptReportResponseSeverity) {
	s.Severity = val
}

// SetSummary sets the value of Summary.
func (s *ReportResponse) SetSummary(val OptString) {
	s.Summary = val
}

// SetDetail sets the value of Detail.
func (s *ReportResponse) SetDetail(val OptString) {
	s.Detail = val
}

// SetDatasources sets the value of Datasources.
func (s *ReportResponse) SetDatasources(val []string) {
	s.Datasources = val
}

// SetIterations sets the value of Iterations.
func (s *ReportResponse) SetIterations(val OptInt) {
	s.Iterations = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ReportResponse) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

func (*ReportResponse) createInspectRes()  {}
func (*ReportResponse) getReportRes()      {}
func (*ReportResponse) receiveWebhookRes() {}

type ReportResponseSeverity string

const (
	ReportResponseSeverityInfo     ReportResponseSeverity = "info"
	ReportResponseSeverityWarning  ReportResponseSeverity = "warning"
	ReportResponseSeverityCritical ReportResponseSeverity = "critical"
)

// AllValues returns all ReportResponseSeverity values.
func (ReportResponseSeverity) AllValues() []ReportResponseSeverity {
	return []ReportResponseSeverity{
		ReportResponseSeverityInfo,
		ReportResponseSeverityWarning,
		ReportResponseSeverityCritical,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ReportResponseSeverity) MarshalText() ([]byte, error) {
	switch s {
	case ReportResponseSeverityInfo:
		return []byte(s), nil
	case ReportResponseSeverityWarning:
		return []byte(s), nil
	case ReportResponseSeverityCritical:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ReportResponseSeverity) UnmarshalText(data []byte) error {
	switch ReportResponseSeverity(data) {
	case ReportResponseSeverityInfo:
		*s = ReportResponseSeverityInfo
		return nil
	case ReportResponseSeverityWarning:
		*s = ReportResponseSeverityWarning
		return nil
	case ReportResponseSeverityCritical:
		*s = ReportResponseSeverityCritical
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ReportResponseStatus string

const (
	ReportResponseStatusPending   ReportResponseStatus = "pending"
	ReportResponseStatusRunning   ReportResponseStatus = "running"
	ReportResponseStatusCompleted ReportResponseStatus = "completed"
	ReportResponseStatusFailed    ReportResponseStatus = "failed"
)

// AllValues returns all ReportResponseStatus values.
func (ReportResponseStatus) AllValues() []ReportResponseStatus {
	return []ReportResponseStatus{
		ReportResponseStatusPending,
		ReportResponseStatusRunning,
		ReportResponseStatusCompleted,
		ReportResponseStatusFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ReportResponseStatus) MarshalText() ([]byte, error) {
	switch s {
	case ReportResponseStatusPending:
		return []byte(s), nil
	case ReportResponseStatusRunning:
		return []byte(s), nil
	case ReportResponseStatusCompleted:
		return []byte(s), nil
	case ReportResponseStatusFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ReportResponseStatus) UnmarshalText(data []byte) error {
	switch ReportResponseStatus(data) {
	case ReportResponseStatusPending:
		*s = ReportResponseStatusPending
		return nil
	case ReportResponseStatusRunning:
		*s = ReportResponseStatusRunning
		return nil
	case ReportResponseStatusCompleted:
		*s = ReportResponseStatusCompleted
		return nil
	case ReportResponseStatusFailed:
		*s = ReportResponseStatusFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ReportResponseTrigger string

const (
	ReportResponseTriggerManual    ReportResponseTrigger = "manual"
	ReportResponseTriggerWebhook   ReportResponseTrigger = "webhook"
	ReportResponseTriggerScheduled ReportResponseTrigger = "scheduled"
)

// AllValues returns all ReportResponseTrigger values.
func (ReportResponseTrigger) AllValues() []ReportResponseTrigger {
	return []ReportResponseTrigger{
		ReportResponseTriggerManual,
		ReportResponseTriggerWebhook,
		ReportResponseTriggerScheduled,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ReportResponseTrigger) MarshalText() ([]byte, error) {
	switch s {
	case ReportResponseTriggerManual:
		return []byte(s), nil
	case ReportResponseTriggerWebhook:
		return []byte(s), nil
	case ReportResponseTriggerScheduled:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ReportResponseTrigger) UnmarshalText(data []byte) error {
	switch ReportResponseTrigger(data) {
	case ReportResponseTriggerManual:
		*s = ReportResponseTriggerManual
		return nil
	case ReportResponseTriggerWebhook:
		*s = ReportResponseTriggerWebhook
		return nil
	case ReportResponseTriggerScheduled:
		*s = ReportResponseTriggerScheduled
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type TestDatasourceOK struct {
	Status string `json:"status"`
}

// GetStatus returns the value of Status.
func (s *TestDatasourceOK) GetStatus() string {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *TestDatasourceOK) SetStatus(val string) {
	s.Status = val
}

func (*TestDatasourceOK) testDatasourceRes() {}
