// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateInspect implements createInspect operation.
	//
	// Trigger a manual inspection.
	//
	// POST /inspect
	CreateInspect(ctx context.Context, req *CreateInspectReq) (CreateInspectRes, error)
	// GetHealth implements getHealth operation.
	//
	// Health check.
	//
	// GET /health
	GetHealth(ctx context.Context) (*GetHealthOK, error)
	// GetReport implements getReport operation.
	//
	// Get a specific report.
	//
	// GET /reports/{id}
	GetReport(ctx context.Context, params GetReportParams) (GetReportRes, error)
	// ListReports implements listReports operation.
	//
	// List inspection reports.
	//
	// GET /reports
	ListReports(ctx context.Context, params ListReportsParams) ([]ReportResponse, error)
	// ReceiveWebhook implements receiveWebhook operation.
	//
	// Receive a webhook trigger.
	//
	// POST /webhook
	ReceiveWebhook(ctx context.Context, req *ReceiveWebhookReq) (ReceiveWebhookRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
