// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateDatasource implements createDatasource operation.
//
// Add a datasource.
//
// POST /datasources
func (UnimplementedHandler) CreateDatasource(ctx context.Context, req *CreateDatasourceRequest) (r CreateDatasourceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateInspect implements createInspect operation.
//
// Trigger a manual inspection.
//
// POST /inspect
func (UnimplementedHandler) CreateInspect(ctx context.Context, req *CreateInspectReq) (r CreateInspectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Health check.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *GetHealthOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetReport implements getReport operation.
//
// Get a specific report.
//
// GET /reports/{id}
func (UnimplementedHandler) GetReport(ctx context.Context, params GetReportParams) (r GetReportRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDatasources implements listDatasources operation.
//
// List datasources.
//
// GET /datasources
func (UnimplementedHandler) ListDatasources(ctx context.Context) (r []DatasourceResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListReports implements listReports operation.
//
// List inspection reports.
//
// GET /reports
func (UnimplementedHandler) ListReports(ctx context.Context, params ListReportsParams) (r []ReportResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ReceiveWebhook implements receiveWebhook operation.
//
// Receive a webhook trigger.
//
// POST /webhook/{source}
func (UnimplementedHandler) ReceiveWebhook(ctx context.Context, req *ReceiveWebhookReq, params ReceiveWebhookParams) (r ReceiveWebhookRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TestDatasource implements testDatasource operation.
//
// Test datasource connection.
//
// GET /datasources/{id}/test
func (UnimplementedHandler) TestDatasource(ctx context.Context, params TestDatasourceParams) (r TestDatasourceRes, _ error) {
	return r, ht.ErrNotImplemented
}
