// Code generated by ogen, DO NOT EDIT.
package api

type CreateInspectRes interface {
	createInspectRes()
}

type GetReportRes interface {
	getReportRes()
}

type ReceiveWebhookRes interface {
	receiveWebhookRes()
}
