// Code generated by ogen, DO NOT EDIT.
package api

type CreateDatasourceRes interface {
	createDatasourceRes()
}

type CreateInspectRes interface {
	createInspectRes()
}

type GetReportRes interface {
	getReportRes()
}

type ReceiveWebhookRes interface {
	receiveWebhookRes()
}

type TestDatasourceRes interface {
	testDatasourceRes()
}
