// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"time"

	"github.com/go-faster/jx"
)

// SetFake set fake values.
func (s *CreateDatasourceRequest) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.URL = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateDatasourceRequestType) SetFake() {
	*s = CreateDatasourceRequestTypePrometheus
}

// SetFake set fake values.
func (s *CreateInspectReq) SetFake() {
	{
		{
			s.Query.SetFake()
		}
	}
	{
		{
			s.MetricQuery.SetFake()
		}
	}
	{
		{
			s.LogQuery.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *DatasourceResponse) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.URL = "string"
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *DatasourceResponseType) SetFake() {
	*s = DatasourceResponseTypePrometheus
}

// SetFake set fake values.
func (s *ErrorResponse) SetFake() {
	{
		{
			s.Error = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetHealthOK) SetFake() {
	{
		{
			s.Status = "string"
		}
	}
}

// SetFake set fake values.
func (s *OptDateTime) SetFake() {
	var elem time.Time
	{
		elem = time.Now()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptInt) SetFake() {
	var elem int
	{
		elem = int(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptReceiveWebhookReqData) SetFake() {
	var elem ReceiveWebhookReqData
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptReportResponseSeverity) SetFake() {
	var elem ReportResponseSeverity
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptString) SetFake() {
	var elem string
	{
		elem = "string"
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *ReceiveWebhookReq) SetFake() {
	{
		{
			s.Source.SetFake()
		}
	}
	{
		{
			s.Alert.SetFake()
		}
	}
	{
		{
			s.Message.SetFake()
		}
	}
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ReceiveWebhookReqData) SetFake() {
	var (
		elem jx.Raw
		m    map[string]jx.Raw = s.init()
	)
	for i := 0; i < 0; i++ {
		m[fmt.Sprintf("fake%d", i)] = elem
	}
}

// SetFake set fake values.
func (s *ReportResponse) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Trigger.SetFake()
		}
	}
	{
		{
			s.TriggerID = "string"
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Severity.SetFake()
		}
	}
	{
		{
			s.Summary.SetFake()
		}
	}
	{
		{
			s.Detail.SetFake()
		}
	}
	{
		{
			s.Datasources = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Datasources = append(s.Datasources, elem)
			}
		}
	}
	{
		{
			s.Iterations.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ReportResponseSeverity) SetFake() {
	*s = ReportResponseSeverityInfo
}

// SetFake set fake values.
func (s *ReportResponseStatus) SetFake() {
	*s = ReportResponseStatusPending
}

// SetFake set fake values.
func (s *ReportResponseTrigger) SetFake() {
	*s = ReportResponseTriggerManual
}

// SetFake set fake values.
func (s *TestDatasourceOK) SetFake() {
	{
		{
			s.Status = "string"
		}
	}
}
