// Code generated by ent, DO NOT EDIT.

package inspectrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/serengeti-sh/meerkat/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldContainsFold(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEQ(FieldUpdateTime, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEQ(FieldName, v))
}

// Interval applies equality check predicate on the "interval" field. It's identical to IntervalEQ.
func Interval(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEQ(FieldInterval, v))
}

// MetricQuery applies equality check predicate on the "metric_query" field. It's identical to MetricQueryEQ.
func MetricQuery(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEQ(FieldMetricQuery, v))
}

// LogQuery applies equality check predicate on the "log_query" field. It's identical to LogQueryEQ.
func LogQuery(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEQ(FieldLogQuery, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEQ(FieldEnabled, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldLTE(FieldUpdateTime, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldContainsFold(FieldName, v))
}

// IntervalEQ applies the EQ predicate on the "interval" field.
func IntervalEQ(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEQ(FieldInterval, v))
}

// IntervalNEQ applies the NEQ predicate on the "interval" field.
func IntervalNEQ(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldNEQ(FieldInterval, v))
}

// IntervalIn applies the In predicate on the "interval" field.
func IntervalIn(vs ...string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldIn(FieldInterval, vs...))
}

// IntervalNotIn applies the NotIn predicate on the "interval" field.
func IntervalNotIn(vs ...string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldNotIn(FieldInterval, vs...))
}

// IntervalGT applies the GT predicate on the "interval" field.
func IntervalGT(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldGT(FieldInterval, v))
}

// IntervalGTE applies the GTE predicate on the "interval" field.
func IntervalGTE(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldGTE(FieldInterval, v))
}

// IntervalLT applies the LT predicate on the "interval" field.
func IntervalLT(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldLT(FieldInterval, v))
}

// IntervalLTE applies the LTE predicate on the "interval" field.
func IntervalLTE(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldLTE(FieldInterval, v))
}

// IntervalContains applies the Contains predicate on the "interval" field.
func IntervalContains(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldContains(FieldInterval, v))
}

// IntervalHasPrefix applies the HasPrefix predicate on the "interval" field.
func IntervalHasPrefix(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldHasPrefix(FieldInterval, v))
}

// IntervalHasSuffix applies the HasSuffix predicate on the "interval" field.
func IntervalHasSuffix(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldHasSuffix(FieldInterval, v))
}

// IntervalEqualFold applies the EqualFold predicate on the "interval" field.
func IntervalEqualFold(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEqualFold(FieldInterval, v))
}

// IntervalContainsFold applies the ContainsFold predicate on the "interval" field.
func IntervalContainsFold(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldContainsFold(FieldInterval, v))
}

// MetricQueryEQ applies the EQ predicate on the "metric_query" field.
func MetricQueryEQ(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEQ(FieldMetricQuery, v))
}

// MetricQueryNEQ applies the NEQ predicate on the "metric_query" field.
func MetricQueryNEQ(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldNEQ(FieldMetricQuery, v))
}

// MetricQueryIn applies the In predicate on the "metric_query" field.
func MetricQueryIn(vs ...string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldIn(FieldMetricQuery, vs...))
}

// MetricQueryNotIn applies the NotIn predicate on the "metric_query" field.
func MetricQueryNotIn(vs ...string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldNotIn(FieldMetricQuery, vs...))
}

// MetricQueryGT applies the GT predicate on the "metric_query" field.
func MetricQueryGT(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldGT(FieldMetricQuery, v))
}

// MetricQueryGTE applies the GTE predicate on the "metric_query" field.
func MetricQueryGTE(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldGTE(FieldMetricQuery, v))
}

// MetricQueryLT applies the LT predicate on the "metric_query" field.
func MetricQueryLT(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldLT(FieldMetricQuery, v))
}

// MetricQueryLTE applies the LTE predicate on the "metric_query" field.
func MetricQueryLTE(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldLTE(FieldMetricQuery, v))
}

// MetricQueryContains applies the Contains predicate on the "metric_query" field.
func MetricQueryContains(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldContains(FieldMetricQuery, v))
}

// MetricQueryHasPrefix applies the HasPrefix predicate on the "metric_query" field.
func MetricQueryHasPrefix(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldHasPrefix(FieldMetricQuery, v))
}

// MetricQueryHasSuffix applies the HasSuffix predicate on the "metric_query" field.
func MetricQueryHasSuffix(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldHasSuffix(FieldMetricQuery, v))
}

// MetricQueryEqualFold applies the EqualFold predicate on the "metric_query" field.
func MetricQueryEqualFold(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEqualFold(FieldMetricQuery, v))
}

// MetricQueryContainsFold applies the ContainsFold predicate on the "metric_query" field.
func MetricQueryContainsFold(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldContainsFold(FieldMetricQuery, v))
}

// LogQueryEQ applies the EQ predicate on the "log_query" field.
func LogQueryEQ(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEQ(FieldLogQuery, v))
}

// LogQueryNEQ applies the NEQ predicate on the "log_query" field.
func LogQueryNEQ(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldNEQ(FieldLogQuery, v))
}

// LogQueryIn applies the In predicate on the "log_query" field.
func LogQueryIn(vs ...string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldIn(FieldLogQuery, vs...))
}

// LogQueryNotIn applies the NotIn predicate on the "log_query" field.
func LogQueryNotIn(vs ...string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldNotIn(FieldLogQuery, vs...))
}

// LogQueryGT applies the GT predicate on the "log_query" field.
func LogQueryGT(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldGT(FieldLogQuery, v))
}

// LogQueryGTE applies the GTE predicate on the "log_query" field.
func LogQueryGTE(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldGTE(FieldLogQuery, v))
}

// LogQueryLT applies the LT predicate on the "log_query" field.
func LogQueryLT(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldLT(FieldLogQuery, v))
}

// LogQueryLTE applies the LTE predicate on the "log_query" field.
func LogQueryLTE(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldLTE(FieldLogQuery, v))
}

// LogQueryContains applies the Contains predicate on the "log_query" field.
func LogQueryContains(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldContains(FieldLogQuery, v))
}

// LogQueryHasPrefix applies the HasPrefix predicate on the "log_query" field.
func LogQueryHasPrefix(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldHasPrefix(FieldLogQuery, v))
}

// LogQueryHasSuffix applies the HasSuffix predicate on the "log_query" field.
func LogQueryHasSuffix(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldHasSuffix(FieldLogQuery, v))
}

// LogQueryEqualFold applies the EqualFold predicate on the "log_query" field.
func LogQueryEqualFold(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEqualFold(FieldLogQuery, v))
}

// LogQueryContainsFold applies the ContainsFold predicate on the "log_query" field.
func LogQueryContainsFold(v string) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldContainsFold(FieldLogQuery, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.InspectRule {
	return predicate.InspectRule(sql.FieldNEQ(FieldEnabled, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InspectRule) predicate.InspectRule {
	return predicate.InspectRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InspectRule) predicate.InspectRule {
	return predicate.InspectRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InspectRule) predicate.InspectRule {
	return predicate.InspectRule(sql.NotPredicates(p))
}
