// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/serengeti-sh/meerkat/internal/ent/predicate"
	"github.com/serengeti-sh/meerkat/internal/ent/report"
)

// ReportUpdate is the builder for updating Report entities.
type ReportUpdate struct {
	config
	hooks    []Hook
	mutation *ReportMutation
}

// Where appends a list predicates to the ReportUpdate builder.
func (_u *ReportUpdate) Where(ps ...predicate.Report) *ReportUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ReportUpdate) SetUpdateTime(v time.Time) *ReportUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetTrigger sets the "trigger" field.
func (_u *ReportUpdate) SetTrigger(v report.Trigger) *ReportUpdate {
	_u.mutation.SetTrigger(v)
	return _u
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableTrigger(v *report.Trigger) *ReportUpdate {
	if v != nil {
		_u.SetTrigger(*v)
	}
	return _u
}

// SetTriggerID sets the "trigger_id" field.
func (_u *ReportUpdate) SetTriggerID(v string) *ReportUpdate {
	_u.mutation.SetTriggerID(v)
	return _u
}

// SetNillableTriggerID sets the "trigger_id" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableTriggerID(v *string) *ReportUpdate {
	if v != nil {
		_u.SetTriggerID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReportUpdate) SetStatus(v report.Status) *ReportUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableStatus(v *report.Status) *ReportUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *ReportUpdate) SetSeverity(v report.Severity) *ReportUpdate {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableSeverity(v *report.Severity) *ReportUpdate {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ReportUpdate) SetSummary(v string) *ReportUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableSummary(v *string) *ReportUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetDetail sets the "detail" field.
func (_u *ReportUpdate) SetDetail(v string) *ReportUpdate {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableDetail(v *string) *ReportUpdate {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// SetQuery sets the "query" field.
func (_u *ReportUpdate) SetQuery(v string) *ReportUpdate {
	_u.mutation.SetQuery(v)
	return _u
}

// SetNillableQuery sets the "query" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableQuery(v *string) *ReportUpdate {
	if v != nil {
		_u.SetQuery(*v)
	}
	return _u
}

// ClearQuery clears the value of the "query" field.
func (_u *ReportUpdate) ClearQuery() *ReportUpdate {
	_u.mutation.ClearQuery()
	return _u
}

// SetDatasources sets the "datasources" field.
func (_u *ReportUpdate) SetDatasources(v []string) *ReportUpdate {
	_u.mutation.SetDatasources(v)
	return _u
}

// AppendDatasources appends value to the "datasources" field.
func (_u *ReportUpdate) AppendDatasources(v []string) *ReportUpdate {
	_u.mutation.AppendDatasources(v)
	return _u
}

// SetIterations sets the "iterations" field.
func (_u *ReportUpdate) SetIterations(v int) *ReportUpdate {
	_u.mutation.ResetIterations()
	_u.mutation.SetIterations(v)
	return _u
}

// SetNillableIterations sets the "iterations" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableIterations(v *int) *ReportUpdate {
	if v != nil {
		_u.SetIterations(*v)
	}
	return _u
}

// AddIterations adds value to the "iterations" field.
func (_u *ReportUpdate) AddIterations(v int) *ReportUpdate {
	_u.mutation.AddIterations(v)
	return _u
}

// Mutation returns the ReportMutation object of the builder.
func (_u *ReportUpdate) Mutation() *ReportMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReportUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReportUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReportUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReportUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReportUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := report.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReportUpdate) check() error {
	if v, ok := _u.mutation.Trigger(); ok {
		if err := report.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "Report.trigger": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := report.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Report.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := report.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "Report.severity": %w`, err)}
		}
	}
	return nil
}

func (_u *ReportUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(report.Table, report.Columns, sqlgraph.NewFieldSpec(report.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(report.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Trigger(); ok {
		_spec.SetField(report.FieldTrigger, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TriggerID(); ok {
		_spec.SetField(report.FieldTriggerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(report.FieldSeverity, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(report.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(report.FieldDetail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Query(); ok {
		_spec.SetField(report.FieldQuery, field.TypeString, value)
	}
	if _u.mutation.QueryCleared() {
		_spec.ClearField(report.FieldQuery, field.TypeString)
	}
	if value, ok := _u.mutation.Datasources(); ok {
		_spec.SetField(report.FieldDatasources, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDatasources(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, report.FieldDatasources, value)
		})
	}
	if value, ok := _u.mutation.Iterations(); ok {
		_spec.SetField(report.FieldIterations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIterations(); ok {
		_spec.AddField(report.FieldIterations, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{report.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReportUpdateOne is the builder for updating a single Report entity.
type ReportUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReportMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *ReportUpdateOne) SetUpdateTime(v time.Time) *ReportUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetTrigger sets the "trigger" field.
func (_u *ReportUpdateOne) SetTrigger(v report.Trigger) *ReportUpdateOne {
	_u.mutation.SetTrigger(v)
	return _u
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableTrigger(v *report.Trigger) *ReportUpdateOne {
	if v != nil {
		_u.SetTrigger(*v)
	}
	return _u
}

// SetTriggerID sets the "trigger_id" field.
func (_u *ReportUpdateOne) SetTriggerID(v string) *ReportUpdateOne {
	_u.mutation.SetTriggerID(v)
	return _u
}

// SetNillableTriggerID sets the "trigger_id" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableTriggerID(v *string) *ReportUpdateOne {
	if v != nil {
		_u.SetTriggerID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReportUpdateOne) SetStatus(v report.Status) *ReportUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableStatus(v *report.Status) *ReportUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *ReportUpdateOne) SetSeverity(v report.Severity) *ReportUpdateOne {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableSeverity(v *report.Severity) *ReportUpdateOne {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ReportUpdateOne) SetSummary(v string) *ReportUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableSummary(v *string) *ReportUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetDetail sets the "detail" field.
func (_u *ReportUpdateOne) SetDetail(v string) *ReportUpdateOne {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableDetail(v *string) *ReportUpdateOne {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// SetQuery sets the "query" field.
func (_u *ReportUpdateOne) SetQuery(v string) *ReportUpdateOne {
	_u.mutation.SetQuery(v)
	return _u
}

// SetNillableQuery sets the "query" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableQuery(v *string) *ReportUpdateOne {
	if v != nil {
		_u.SetQuery(*v)
	}
	return _u
}

// ClearQuery clears the value of the "query" field.
func (_u *ReportUpdateOne) ClearQuery() *ReportUpdateOne {
	_u.mutation.ClearQuery()
	return _u
}

// SetDatasources sets the "datasources" field.
func (_u *ReportUpdateOne) SetDatasources(v []string) *ReportUpdateOne {
	_u.mutation.SetDatasources(v)
	return _u
}

// AppendDatasources appends value to the "datasources" field.
func (_u *ReportUpdateOne) AppendDatasources(v []string) *ReportUpdateOne {
	_u.mutation.AppendDatasources(v)
	return _u
}

// SetIterations sets the "iterations" field.
func (_u *ReportUpdateOne) SetIterations(v int) *ReportUpdateOne {
	_u.mutation.ResetIterations()
	_u.mutation.SetIterations(v)
	return _u
}

// SetNillableIterations sets the "iterations" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableIterations(v *int) *ReportUpdateOne {
	if v != nil {
		_u.SetIterations(*v)
	}
	return _u
}

// AddIterations adds value to the "iterations" field.
func (_u *ReportUpdateOne) AddIterations(v int) *ReportUpdateOne {
	_u.mutation.AddIterations(v)
	return _u
}

// Mutation returns the ReportMutation object of the builder.
func (_u *ReportUpdateOne) Mutation() *ReportMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReportUpdate builder.
func (_u *ReportUpdateOne) Where(ps ...predicate.Report) *ReportUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReportUpdateOne) Select(field string, fields ...string) *ReportUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Report entity.
func (_u *ReportUpdateOne) Save(ctx context.Context) (*Report, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReportUpdateOne) SaveX(ctx context.Context) *Report {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReportUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReportUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReportUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := report.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReportUpdateOne) check() error {
	if v, ok := _u.mutation.Trigger(); ok {
		if err := report.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "Report.trigger": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := report.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Report.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := report.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "Report.severity": %w`, err)}
		}
	}
	return nil
}

func (_u *ReportUpdateOne) sqlSave(ctx context.Context) (_node *Report, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(report.Table, report.Columns, sqlgraph.NewFieldSpec(report.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Report.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, report.FieldID)
		for _, f := range fields {
			if !report.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != report.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(report.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Trigger(); ok {
		_spec.SetField(report.FieldTrigger, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TriggerID(); ok {
		_spec.SetField(report.FieldTriggerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(report.FieldSeverity, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(report.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(report.FieldDetail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Query(); ok {
		_spec.SetField(report.FieldQuery, field.TypeString, value)
	}
	if _u.mutation.QueryCleared() {
		_spec.ClearField(report.FieldQuery, field.TypeString)
	}
	if value, ok := _u.mutation.Datasources(); ok {
		_spec.SetField(report.FieldDatasources, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDatasources(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, report.FieldDatasources, value)
		})
	}
	if value, ok := _u.mutation.Iterations(); ok {
		_spec.SetField(report.FieldIterations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIterations(); ok {
		_spec.AddField(report.FieldIterations, field.TypeInt, value)
	}
	_node = &Report{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{report.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
