// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package datasourceMocks

import (
	"context"

	"github.com/mandacode-labs/inspector/internal/datasource"
	mock "github.com/stretchr/testify/mock"
)

// NewProviderMock creates a new instance of ProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProviderMock {
	mock := &ProviderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProviderMock is an autogenerated mock type for the Provider type
type ProviderMock struct {
	mock.Mock
}

type ProviderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ProviderMock) EXPECT() *ProviderMock_Expecter {
	return &ProviderMock_Expecter{mock: &_m.Mock}
}

// LogsQuerier provides a mock function for the type ProviderMock
func (_mock *ProviderMock) LogsQuerier() (datasource.LogsQuerier, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LogsQuerier")
	}

	var r0 datasource.LogsQuerier
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (datasource.LogsQuerier, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() datasource.LogsQuerier); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(datasource.LogsQuerier)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// ProviderMock_LogsQuerier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogsQuerier'
type ProviderMock_LogsQuerier_Call struct {
	*mock.Call
}

// LogsQuerier is a helper method to define mock.On call
func (_e *ProviderMock_Expecter) LogsQuerier() *ProviderMock_LogsQuerier_Call {
	return &ProviderMock_LogsQuerier_Call{Call: _e.mock.On("LogsQuerier")}
}

func (_c *ProviderMock_LogsQuerier_Call) Run(run func()) *ProviderMock_LogsQuerier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProviderMock_LogsQuerier_Call) Return(logsQuerier datasource.LogsQuerier, b bool) *ProviderMock_LogsQuerier_Call {
	_c.Call.Return(logsQuerier, b)
	return _c
}

func (_c *ProviderMock_LogsQuerier_Call) RunAndReturn(run func() (datasource.LogsQuerier, bool)) *ProviderMock_LogsQuerier_Call {
	_c.Call.Return(run)
	return _c
}

// MetricsQuerier provides a mock function for the type ProviderMock
func (_mock *ProviderMock) MetricsQuerier() (datasource.MetricsQuerier, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MetricsQuerier")
	}

	var r0 datasource.MetricsQuerier
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (datasource.MetricsQuerier, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() datasource.MetricsQuerier); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(datasource.MetricsQuerier)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// ProviderMock_MetricsQuerier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MetricsQuerier'
type ProviderMock_MetricsQuerier_Call struct {
	*mock.Call
}

// MetricsQuerier is a helper method to define mock.On call
func (_e *ProviderMock_Expecter) MetricsQuerier() *ProviderMock_MetricsQuerier_Call {
	return &ProviderMock_MetricsQuerier_Call{Call: _e.mock.On("MetricsQuerier")}
}

func (_c *ProviderMock_MetricsQuerier_Call) Run(run func()) *ProviderMock_MetricsQuerier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProviderMock_MetricsQuerier_Call) Return(metricsQuerier datasource.MetricsQuerier, b bool) *ProviderMock_MetricsQuerier_Call {
	_c.Call.Return(metricsQuerier, b)
	return _c
}

func (_c *ProviderMock_MetricsQuerier_Call) RunAndReturn(run func() (datasource.MetricsQuerier, bool)) *ProviderMock_MetricsQuerier_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type ProviderMock
func (_mock *ProviderMock) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ProviderMock_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type ProviderMock_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *ProviderMock_Expecter) Name() *ProviderMock_Name_Call {
	return &ProviderMock_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *ProviderMock_Name_Call) Run(run func()) *ProviderMock_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProviderMock_Name_Call) Return(s string) *ProviderMock_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ProviderMock_Name_Call) RunAndReturn(run func() string) *ProviderMock_Name_Call {
	_c.Call.Return(run)
	return _c
}

// TestConnection provides a mock function for the type ProviderMock
func (_mock *ProviderMock) TestConnection(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TestConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProviderMock_TestConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestConnection'
type ProviderMock_TestConnection_Call struct {
	*mock.Call
}

// TestConnection is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ProviderMock_Expecter) TestConnection(ctx interface{}) *ProviderMock_TestConnection_Call {
	return &ProviderMock_TestConnection_Call{Call: _e.mock.On("TestConnection", ctx)}
}

func (_c *ProviderMock_TestConnection_Call) Run(run func(ctx context.Context)) *ProviderMock_TestConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ProviderMock_TestConnection_Call) Return(err error) *ProviderMock_TestConnection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProviderMock_TestConnection_Call) RunAndReturn(run func(ctx context.Context) error) *ProviderMock_TestConnection_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type ProviderMock
func (_mock *ProviderMock) Type() datasource.Type {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 datasource.Type
	if returnFunc, ok := ret.Get(0).(func() datasource.Type); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(datasource.Type)
	}
	return r0
}

// ProviderMock_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type ProviderMock_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *ProviderMock_Expecter) Type() *ProviderMock_Type_Call {
	return &ProviderMock_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *ProviderMock_Type_Call) Run(run func()) *ProviderMock_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProviderMock_Type_Call) Return(typeParam datasource.Type) *ProviderMock_Type_Call {
	_c.Call.Return(typeParam)
	return _c
}

func (_c *ProviderMock_Type_Call) RunAndReturn(run func() datasource.Type) *ProviderMock_Type_Call {
	_c.Call.Return(run)
	return _c
}
