// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package datasourceMocks

import (
	"context"

	"github.com/mandacode-labs/inspector/internal/datasource"
	mock "github.com/stretchr/testify/mock"
)

// NewLogsQuerierMock creates a new instance of LogsQuerierMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogsQuerierMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogsQuerierMock {
	mock := &LogsQuerierMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LogsQuerierMock is an autogenerated mock type for the LogsQuerier type
type LogsQuerierMock struct {
	mock.Mock
}

type LogsQuerierMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LogsQuerierMock) EXPECT() *LogsQuerierMock_Expecter {
	return &LogsQuerierMock_Expecter{mock: &_m.Mock}
}

// QueryLogs provides a mock function for the type LogsQuerierMock
func (_mock *LogsQuerierMock) QueryLogs(ctx context.Context, query string, limit int) ([]datasource.LogEntry, error) {
	ret := _mock.Called(ctx, query, limit)

	if len(ret) == 0 {
		panic("no return value specified for QueryLogs")
	}

	var r0 []datasource.LogEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]datasource.LogEntry, error)); ok {
		return returnFunc(ctx, query, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []datasource.LogEntry); ok {
		r0 = returnFunc(ctx, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datasource.LogEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, query, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LogsQuerierMock_QueryLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryLogs'
type LogsQuerierMock_QueryLogs_Call struct {
	*mock.Call
}

// QueryLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - limit int
func (_e *LogsQuerierMock_Expecter) QueryLogs(ctx interface{}, query interface{}, limit interface{}) *LogsQuerierMock_QueryLogs_Call {
	return &LogsQuerierMock_QueryLogs_Call{Call: _e.mock.On("QueryLogs", ctx, query, limit)}
}

func (_c *LogsQuerierMock_QueryLogs_Call) Run(run func(ctx context.Context, query string, limit int)) *LogsQuerierMock_QueryLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LogsQuerierMock_QueryLogs_Call) Return(logEntrys []datasource.LogEntry, err error) *LogsQuerierMock_QueryLogs_Call {
	_c.Call.Return(logEntrys, err)
	return _c
}

func (_c *LogsQuerierMock_QueryLogs_Call) RunAndReturn(run func(ctx context.Context, query string, limit int) ([]datasource.LogEntry, error)) *LogsQuerierMock_QueryLogs_Call {
	_c.Call.Return(run)
	return _c
}
