// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package datasourceMocks

import (
	"context"

	"github.com/mandacode-labs/inspector/internal/datasource"
	"github.com/mandacode-labs/inspector/internal/errors"
	mock "github.com/stretchr/testify/mock"
)

// NewDatasourceServiceMock creates a new instance of DatasourceServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatasourceServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatasourceServiceMock {
	mock := &DatasourceServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DatasourceServiceMock is an autogenerated mock type for the DatasourceService type
type DatasourceServiceMock struct {
	mock.Mock
}

type DatasourceServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DatasourceServiceMock) EXPECT() *DatasourceServiceMock_Expecter {
	return &DatasourceServiceMock_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type DatasourceServiceMock
func (_mock *DatasourceServiceMock) List(ctx context.Context) ([]*datasource.Datasource, errors.Error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*datasource.Datasource
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*datasource.Datasource, errors.Error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*datasource.Datasource); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*datasource.Datasource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) errors.Error); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// DatasourceServiceMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type DatasourceServiceMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DatasourceServiceMock_Expecter) List(ctx interface{}) *DatasourceServiceMock_List_Call {
	return &DatasourceServiceMock_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *DatasourceServiceMock_List_Call) Run(run func(ctx context.Context)) *DatasourceServiceMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DatasourceServiceMock_List_Call) Return(datasources []*datasource.Datasource, error errors.Error) *DatasourceServiceMock_List_Call {
	_c.Call.Return(datasources, error)
	return _c
}

func (_c *DatasourceServiceMock_List_Call) RunAndReturn(run func(ctx context.Context) ([]*datasource.Datasource, errors.Error)) *DatasourceServiceMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// TestConnection provides a mock function for the type DatasourceServiceMock
func (_mock *DatasourceServiceMock) TestConnection(ctx context.Context, name string) errors.Error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for TestConnection")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) errors.Error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// DatasourceServiceMock_TestConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestConnection'
type DatasourceServiceMock_TestConnection_Call struct {
	*mock.Call
}

// TestConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *DatasourceServiceMock_Expecter) TestConnection(ctx interface{}, name interface{}) *DatasourceServiceMock_TestConnection_Call {
	return &DatasourceServiceMock_TestConnection_Call{Call: _e.mock.On("TestConnection", ctx, name)}
}

func (_c *DatasourceServiceMock_TestConnection_Call) Run(run func(ctx context.Context, name string)) *DatasourceServiceMock_TestConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatasourceServiceMock_TestConnection_Call) Return(error errors.Error) *DatasourceServiceMock_TestConnection_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *DatasourceServiceMock_TestConnection_Call) RunAndReturn(run func(ctx context.Context, name string) errors.Error) *DatasourceServiceMock_TestConnection_Call {
	_c.Call.Return(run)
	return _c
}
