// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package schedulermocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewSchedulerMock creates a new instance of SchedulerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSchedulerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SchedulerMock {
	mock := &SchedulerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SchedulerMock is an autogenerated mock type for the Scheduler type
type SchedulerMock struct {
	mock.Mock
}

type SchedulerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SchedulerMock) EXPECT() *SchedulerMock_Expecter {
	return &SchedulerMock_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type SchedulerMock
func (_mock *SchedulerMock) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SchedulerMock_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type SchedulerMock_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SchedulerMock_Expecter) Start(ctx interface{}) *SchedulerMock_Start_Call {
	return &SchedulerMock_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *SchedulerMock_Start_Call) Run(run func(ctx context.Context)) *SchedulerMock_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SchedulerMock_Start_Call) Return(err error) *SchedulerMock_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SchedulerMock_Start_Call) RunAndReturn(run func(ctx context.Context) error) *SchedulerMock_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type SchedulerMock
func (_mock *SchedulerMock) Stop() {
	_mock.Called()
	return
}

// SchedulerMock_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type SchedulerMock_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *SchedulerMock_Expecter) Stop() *SchedulerMock_Stop_Call {
	return &SchedulerMock_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *SchedulerMock_Stop_Call) Run(run func()) *SchedulerMock_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SchedulerMock_Stop_Call) Return() *SchedulerMock_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *SchedulerMock_Stop_Call) RunAndReturn(run func()) *SchedulerMock_Stop_Call {
	_c.Run(run)
	return _c
}
