// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package schedulemocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewServiceMock creates a new instance of ServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceMock is an autogenerated mock type for the Service type
type ServiceMock struct {
	mock.Mock
}

type ServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceMock) EXPECT() *ServiceMock_Expecter {
	return &ServiceMock_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type ServiceMock
func (_mock *ServiceMock) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ServiceMock_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type ServiceMock_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ServiceMock_Expecter) Start(ctx interface{}) *ServiceMock_Start_Call {
	return &ServiceMock_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *ServiceMock_Start_Call) Run(run func(ctx context.Context)) *ServiceMock_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceMock_Start_Call) Return(err error) *ServiceMock_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ServiceMock_Start_Call) RunAndReturn(run func(ctx context.Context) error) *ServiceMock_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type ServiceMock
func (_mock *ServiceMock) Stop() {
	_mock.Called()
	return
}

// ServiceMock_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type ServiceMock_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *ServiceMock_Expecter) Stop() *ServiceMock_Stop_Call {
	return &ServiceMock_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *ServiceMock_Stop_Call) Run(run func()) *ServiceMock_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceMock_Stop_Call) Return() *ServiceMock_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceMock_Stop_Call) RunAndReturn(run func()) *ServiceMock_Stop_Call {
	_c.Run(run)
	return _c
}
