// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/vectors/v1/vectors.proto

package vectorspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchResult represents a single matching log entry.
type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Service       string                 `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_api_proto_vectors_v1_vectors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vectors_v1_vectors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_api_proto_vectors_v1_vectors_proto_rawDescGZIP(), []int{0}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SearchResult) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *SearchResult) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *SearchResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// SearchRequest contains the query parameters.
type SearchRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Query            string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit            int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Service          string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Severity         string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	TimeRangeSeconds int64                  `protobuf:"varint,5,opt,name=time_range_seconds,json=timeRangeSeconds,proto3" json:"time_range_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_proto_vectors_v1_vectors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vectors_v1_vectors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_vectors_v1_vectors_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *SearchRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *SearchRequest) GetTimeRangeSeconds() int64 {
	if x != nil {
		return x.TimeRangeSeconds
	}
	return 0
}

// SearchResponse returns the search results.
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_proto_vectors_v1_vectors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vectors_v1_vectors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_vectors_v1_vectors_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// GetContextRequest retrieves log context for a specific incident.
type GetContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextRequest) Reset() {
	*x = GetContextRequest{}
	mi := &file_api_proto_vectors_v1_vectors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextRequest) ProtoMessage() {}

func (x *GetContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vectors_v1_vectors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextRequest.ProtoReflect.Descriptor instead.
func (*GetContextRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_vectors_v1_vectors_proto_rawDescGZIP(), []int{3}
}

func (x *GetContextRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetContextRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetContextRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetContextRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetContextResponse returns the contextual log entries.
type GetContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextResponse) Reset() {
	*x = GetContextResponse{}
	mi := &file_api_proto_vectors_v1_vectors_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextResponse) ProtoMessage() {}

func (x *GetContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vectors_v1_vectors_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextResponse.ProtoReflect.Descriptor instead.
func (*GetContextResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_vectors_v1_vectors_proto_rawDescGZIP(), []int{4}
}

func (x *GetContextResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_api_proto_vectors_v1_vectors_proto protoreflect.FileDescriptor

const file_api_proto_vectors_v1_vectors_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/vectors/v1/vectors.proto\x12\n" +
	"vectors.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x01\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x9f\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12,\n" +
	"\x12time_range_seconds\x18\x05 \x01(\x03R\x10timeRangeSeconds\"D\n" +
	"\x0eSearchResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.vectors.v1.SearchResultR\aresults\"\xb5\x01\n" +
	"\x11GetContextRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"H\n" +
	"\x12GetContextResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.vectors.v1.SearchResultR\aresults2\x97\x01\n" +
	"\aService\x12?\n" +
	"\x06Search\x12\x19.vectors.v1.SearchRequest\x1a\x1a.vectors.v1.SearchResponse\x12K\n" +
	"\n" +
	"GetContext\x12\x1d.vectors.v1.GetContextRequest\x1a\x1e.vectors.v1.GetContextResponseB4Z2github.com/serengeti-sh/meerkat/internal/vectorspbb\x06proto3"

var (
	file_api_proto_vectors_v1_vectors_proto_rawDescOnce sync.Once
	file_api_proto_vectors_v1_vectors_proto_rawDescData []byte
)

func file_api_proto_vectors_v1_vectors_proto_rawDescGZIP() []byte {
	file_api_proto_vectors_v1_vectors_proto_rawDescOnce.Do(func() {
		file_api_proto_vectors_v1_vectors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_vectors_v1_vectors_proto_rawDesc), len(file_api_proto_vectors_v1_vectors_proto_rawDesc)))
	})
	return file_api_proto_vectors_v1_vectors_proto_rawDescData
}

var file_api_proto_vectors_v1_vectors_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_vectors_v1_vectors_proto_goTypes = []any{
	(*SearchResult)(nil),          // 0: vectors.v1.SearchResult
	(*SearchRequest)(nil),         // 1: vectors.v1.SearchRequest
	(*SearchResponse)(nil),        // 2: vectors.v1.SearchResponse
	(*GetContextRequest)(nil),     // 3: vectors.v1.GetContextRequest
	(*GetContextResponse)(nil),    // 4: vectors.v1.GetContextResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_api_proto_vectors_v1_vectors_proto_depIdxs = []int32{
	5, // 0: vectors.v1.SearchResult.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: vectors.v1.SearchResponse.results:type_name -> vectors.v1.SearchResult
	5, // 2: vectors.v1.GetContextRequest.start_time:type_name -> google.protobuf.Timestamp
	5, // 3: vectors.v1.GetContextRequest.end_time:type_name -> google.protobuf.Timestamp
	0, // 4: vectors.v1.GetContextResponse.results:type_name -> vectors.v1.SearchResult
	1, // 5: vectors.v1.Service.Search:input_type -> vectors.v1.SearchRequest
	3, // 6: vectors.v1.Service.GetContext:input_type -> vectors.v1.GetContextRequest
	2, // 7: vectors.v1.Service.Search:output_type -> vectors.v1.SearchResponse
	4, // 8: vectors.v1.Service.GetContext:output_type -> vectors.v1.GetContextResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_vectors_v1_vectors_proto_init() }
func file_api_proto_vectors_v1_vectors_proto_init() {
	if File_api_proto_vectors_v1_vectors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_vectors_v1_vectors_proto_rawDesc), len(file_api_proto_vectors_v1_vectors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_vectors_v1_vectors_proto_goTypes,
		DependencyIndexes: file_api_proto_vectors_v1_vectors_proto_depIdxs,
		MessageInfos:      file_api_proto_vectors_v1_vectors_proto_msgTypes,
	}.Build()
	File_api_proto_vectors_v1_vectors_proto = out.File
	file_api_proto_vectors_v1_vectors_proto_goTypes = nil
	file_api_proto_vectors_v1_vectors_proto_depIdxs = nil
}
