// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// InspectRulesColumns holds the columns for the "inspect_rules" table.
	InspectRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "interval", Type: field.TypeString, Size: 32},
		{Name: "metric_query", Type: field.TypeString, Default: ""},
		{Name: "log_query", Type: field.TypeString, Default: ""},
		{Name: "enabled", Type: field.TypeBool, Default: true},
	}
	// InspectRulesTable holds the schema information for the "inspect_rules" table.
	InspectRulesTable = &schema.Table{
		Name:       "inspect_rules",
		Columns:    InspectRulesColumns,
		PrimaryKey: []*schema.Column{InspectRulesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "inspectrule_name",
				Unique:  true,
				Columns: []*schema.Column{InspectRulesColumns[3]},
			},
			{
				Name:    "inspectrule_enabled",
				Unique:  false,
				Columns: []*schema.Column{InspectRulesColumns[7]},
			},
		},
	}
	// ReportsColumns holds the columns for the "reports" table.
	ReportsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "trigger", Type: field.TypeEnum, Enums: []string{"manual", "webhook", "scheduled"}},
		{Name: "trigger_id", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "running", "completed", "failed"}, Default: "pending"},
		{Name: "severity", Type: field.TypeEnum, Enums: []string{"info", "warning", "critical"}, Default: "info"},
		{Name: "summary", Type: field.TypeString, Default: ""},
		{Name: "detail", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "query", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "datasources", Type: field.TypeJSON},
		{Name: "iterations", Type: field.TypeInt, Default: 0},
	}
	// ReportsTable holds the schema information for the "reports" table.
	ReportsTable = &schema.Table{
		Name:       "reports",
		Columns:    ReportsColumns,
		PrimaryKey: []*schema.Column{ReportsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "report_trigger",
				Unique:  false,
				Columns: []*schema.Column{ReportsColumns[3]},
			},
			{
				Name:    "report_status",
				Unique:  false,
				Columns: []*schema.Column{ReportsColumns[5]},
			},
			{
				Name:    "report_severity",
				Unique:  false,
				Columns: []*schema.Column{ReportsColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		InspectRulesTable,
		ReportsTable,
	}
)

func init() {
	InspectRulesTable.Annotation = &entsql.Annotation{
		Table: "inspect_rules",
	}
	ReportsTable.Annotation = &entsql.Annotation{
		Table: "reports",
	}
}
