// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package errorsMocks

import (
	"github.com/serengeti-sh/meerkat/internal/errors"
	mock "github.com/stretchr/testify/mock"
)

// NewErrorMock creates a new instance of ErrorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorMock {
	mock := &ErrorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ErrorMock is an autogenerated mock type for the Error type
type ErrorMock struct {
	mock.Mock
}

type ErrorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ErrorMock) EXPECT() *ErrorMock_Expecter {
	return &ErrorMock_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type ErrorMock
func (_mock *ErrorMock) Error() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ErrorMock_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type ErrorMock_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *ErrorMock_Expecter) Error() *ErrorMock_Error_Call {
	return &ErrorMock_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *ErrorMock_Error_Call) Run(run func()) *ErrorMock_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ErrorMock_Error_Call) Return(s string) *ErrorMock_Error_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ErrorMock_Error_Call) RunAndReturn(run func() string) *ErrorMock_Error_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type ErrorMock
func (_mock *ErrorMock) Type() errors.ErrorType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 errors.ErrorType
	if returnFunc, ok := ret.Get(0).(func() errors.ErrorType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(errors.ErrorType)
	}
	return r0
}

// ErrorMock_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type ErrorMock_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *ErrorMock_Expecter) Type() *ErrorMock_Type_Call {
	return &ErrorMock_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *ErrorMock_Type_Call) Run(run func()) *ErrorMock_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ErrorMock_Type_Call) Return(errorType errors.ErrorType) *ErrorMock_Type_Call {
	_c.Call.Return(errorType)
	return _c
}

func (_c *ErrorMock_Type_Call) RunAndReturn(run func() errors.ErrorType) *ErrorMock_Type_Call {
	_c.Call.Return(run)
	return _c
}
