// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package reporterMocks

import (
	"context"

	"github.com/mandacode-labs/inspector/internal/reporter"
	mock "github.com/stretchr/testify/mock"
)

// NewReportChannelMock creates a new instance of ReportChannelMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportChannelMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportChannelMock {
	mock := &ReportChannelMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ReportChannelMock is an autogenerated mock type for the ReportChannel type
type ReportChannelMock struct {
	mock.Mock
}

type ReportChannelMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportChannelMock) EXPECT() *ReportChannelMock_Expecter {
	return &ReportChannelMock_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type ReportChannelMock
func (_mock *ReportChannelMock) Send(ctx context.Context, report *reporter.ReportData) error {
	ret := _mock.Called(ctx, report)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *reporter.ReportData) error); ok {
		r0 = returnFunc(ctx, report)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReportChannelMock_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type ReportChannelMock_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - report *reporter.ReportData
func (_e *ReportChannelMock_Expecter) Send(ctx interface{}, report interface{}) *ReportChannelMock_Send_Call {
	return &ReportChannelMock_Send_Call{Call: _e.mock.On("Send", ctx, report)}
}

func (_c *ReportChannelMock_Send_Call) Run(run func(ctx context.Context, report *reporter.ReportData)) *ReportChannelMock_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *reporter.ReportData
		if args[1] != nil {
			arg1 = args[1].(*reporter.ReportData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReportChannelMock_Send_Call) Return(err error) *ReportChannelMock_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReportChannelMock_Send_Call) RunAndReturn(run func(ctx context.Context, report *reporter.ReportData) error) *ReportChannelMock_Send_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type ReportChannelMock
func (_mock *ReportChannelMock) Type() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ReportChannelMock_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type ReportChannelMock_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *ReportChannelMock_Expecter) Type() *ReportChannelMock_Type_Call {
	return &ReportChannelMock_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *ReportChannelMock_Type_Call) Run(run func()) *ReportChannelMock_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ReportChannelMock_Type_Call) Return(s string) *ReportChannelMock_Type_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ReportChannelMock_Type_Call) RunAndReturn(run func() string) *ReportChannelMock_Type_Call {
	_c.Call.Return(run)
	return _c
}
