// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/serengeti-sh/meerkat/ent/inspectrule"
)

// InspectRuleCreate is the builder for creating a InspectRule entity.
type InspectRuleCreate struct {
	config
	mutation *InspectRuleMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *InspectRuleCreate) SetCreateTime(v time.Time) *InspectRuleCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *InspectRuleCreate) SetNillableCreateTime(v *time.Time) *InspectRuleCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *InspectRuleCreate) SetUpdateTime(v time.Time) *InspectRuleCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *InspectRuleCreate) SetNillableUpdateTime(v *time.Time) *InspectRuleCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *InspectRuleCreate) SetName(v string) *InspectRuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetInterval sets the "interval" field.
func (_c *InspectRuleCreate) SetInterval(v string) *InspectRuleCreate {
	_c.mutation.SetInterval(v)
	return _c
}

// SetMetricQuery sets the "metric_query" field.
func (_c *InspectRuleCreate) SetMetricQuery(v string) *InspectRuleCreate {
	_c.mutation.SetMetricQuery(v)
	return _c
}

// SetNillableMetricQuery sets the "metric_query" field if the given value is not nil.
func (_c *InspectRuleCreate) SetNillableMetricQuery(v *string) *InspectRuleCreate {
	if v != nil {
		_c.SetMetricQuery(*v)
	}
	return _c
}

// SetLogQuery sets the "log_query" field.
func (_c *InspectRuleCreate) SetLogQuery(v string) *InspectRuleCreate {
	_c.mutation.SetLogQuery(v)
	return _c
}

// SetNillableLogQuery sets the "log_query" field if the given value is not nil.
func (_c *InspectRuleCreate) SetNillableLogQuery(v *string) *InspectRuleCreate {
	if v != nil {
		_c.SetLogQuery(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *InspectRuleCreate) SetEnabled(v bool) *InspectRuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *InspectRuleCreate) SetNillableEnabled(v *bool) *InspectRuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InspectRuleCreate) SetID(v string) *InspectRuleCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the InspectRuleMutation object of the builder.
func (_c *InspectRuleCreate) Mutation() *InspectRuleMutation {
	return _c.mutation
}

// Save creates the InspectRule in the database.
func (_c *InspectRuleCreate) Save(ctx context.Context) (*InspectRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InspectRuleCreate) SaveX(ctx context.Context) *InspectRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InspectRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InspectRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InspectRuleCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := inspectrule.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := inspectrule.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.MetricQuery(); !ok {
		v := inspectrule.DefaultMetricQuery
		_c.mutation.SetMetricQuery(v)
	}
	if _, ok := _c.mutation.LogQuery(); !ok {
		v := inspectrule.DefaultLogQuery
		_c.mutation.SetLogQuery(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := inspectrule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InspectRuleCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "InspectRule.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "InspectRule.update_time"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "InspectRule.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := inspectrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "InspectRule.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Interval(); !ok {
		return &ValidationError{Name: "interval", err: errors.New(`ent: missing required field "InspectRule.interval"`)}
	}
	if v, ok := _c.mutation.Interval(); ok {
		if err := inspectrule.IntervalValidator(v); err != nil {
			return &ValidationError{Name: "interval", err: fmt.Errorf(`ent: validator failed for field "InspectRule.interval": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MetricQuery(); !ok {
		return &ValidationError{Name: "metric_query", err: errors.New(`ent: missing required field "InspectRule.metric_query"`)}
	}
	if _, ok := _c.mutation.LogQuery(); !ok {
		return &ValidationError{Name: "log_query", err: errors.New(`ent: missing required field "InspectRule.log_query"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "InspectRule.enabled"`)}
	}
	return nil
}

func (_c *InspectRuleCreate) sqlSave(ctx context.Context) (*InspectRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected InspectRule.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InspectRuleCreate) createSpec() (*InspectRule, *sqlgraph.CreateSpec) {
	var (
		_node = &InspectRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(inspectrule.Table, sqlgraph.NewFieldSpec(inspectrule.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(inspectrule.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(inspectrule.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(inspectrule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Interval(); ok {
		_spec.SetField(inspectrule.FieldInterval, field.TypeString, value)
		_node.Interval = value
	}
	if value, ok := _c.mutation.MetricQuery(); ok {
		_spec.SetField(inspectrule.FieldMetricQuery, field.TypeString, value)
		_node.MetricQuery = value
	}
	if value, ok := _c.mutation.LogQuery(); ok {
		_spec.SetField(inspectrule.FieldLogQuery, field.TypeString, value)
		_node.LogQuery = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(inspectrule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	return _node, _spec
}

// InspectRuleCreateBulk is the builder for creating many InspectRule entities in bulk.
type InspectRuleCreateBulk struct {
	config
	err      error
	builders []*InspectRuleCreate
}

// Save creates the InspectRule entities in the database.
func (_c *InspectRuleCreateBulk) Save(ctx context.Context) ([]*InspectRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InspectRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InspectRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InspectRuleCreateBulk) SaveX(ctx context.Context) []*InspectRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InspectRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InspectRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
