// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/serengeti-sh/meerkat/ent/inspectrule"
	"github.com/serengeti-sh/meerkat/ent/predicate"
)

// InspectRuleUpdate is the builder for updating InspectRule entities.
type InspectRuleUpdate struct {
	config
	hooks    []Hook
	mutation *InspectRuleMutation
}

// Where appends a list predicates to the InspectRuleUpdate builder.
func (_u *InspectRuleUpdate) Where(ps ...predicate.InspectRule) *InspectRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *InspectRuleUpdate) SetUpdateTime(v time.Time) *InspectRuleUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetName sets the "name" field.
func (_u *InspectRuleUpdate) SetName(v string) *InspectRuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *InspectRuleUpdate) SetNillableName(v *string) *InspectRuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetInterval sets the "interval" field.
func (_u *InspectRuleUpdate) SetInterval(v string) *InspectRuleUpdate {
	_u.mutation.SetInterval(v)
	return _u
}

// SetNillableInterval sets the "interval" field if the given value is not nil.
func (_u *InspectRuleUpdate) SetNillableInterval(v *string) *InspectRuleUpdate {
	if v != nil {
		_u.SetInterval(*v)
	}
	return _u
}

// SetMetricQuery sets the "metric_query" field.
func (_u *InspectRuleUpdate) SetMetricQuery(v string) *InspectRuleUpdate {
	_u.mutation.SetMetricQuery(v)
	return _u
}

// SetNillableMetricQuery sets the "metric_query" field if the given value is not nil.
func (_u *InspectRuleUpdate) SetNillableMetricQuery(v *string) *InspectRuleUpdate {
	if v != nil {
		_u.SetMetricQuery(*v)
	}
	return _u
}

// SetLogQuery sets the "log_query" field.
func (_u *InspectRuleUpdate) SetLogQuery(v string) *InspectRuleUpdate {
	_u.mutation.SetLogQuery(v)
	return _u
}

// SetNillableLogQuery sets the "log_query" field if the given value is not nil.
func (_u *InspectRuleUpdate) SetNillableLogQuery(v *string) *InspectRuleUpdate {
	if v != nil {
		_u.SetLogQuery(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *InspectRuleUpdate) SetEnabled(v bool) *InspectRuleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *InspectRuleUpdate) SetNillableEnabled(v *bool) *InspectRuleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the InspectRuleMutation object of the builder.
func (_u *InspectRuleUpdate) Mutation() *InspectRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InspectRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InspectRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InspectRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InspectRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InspectRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := inspectrule.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InspectRuleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := inspectrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "InspectRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Interval(); ok {
		if err := inspectrule.IntervalValidator(v); err != nil {
			return &ValidationError{Name: "interval", err: fmt.Errorf(`ent: validator failed for field "InspectRule.interval": %w`, err)}
		}
	}
	return nil
}

func (_u *InspectRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(inspectrule.Table, inspectrule.Columns, sqlgraph.NewFieldSpec(inspectrule.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(inspectrule.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(inspectrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Interval(); ok {
		_spec.SetField(inspectrule.FieldInterval, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetricQuery(); ok {
		_spec.SetField(inspectrule.FieldMetricQuery, field.TypeString, value)
	}
	if value, ok := _u.mutation.LogQuery(); ok {
		_spec.SetField(inspectrule.FieldLogQuery, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(inspectrule.FieldEnabled, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inspectrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InspectRuleUpdateOne is the builder for updating a single InspectRule entity.
type InspectRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InspectRuleMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *InspectRuleUpdateOne) SetUpdateTime(v time.Time) *InspectRuleUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetName sets the "name" field.
func (_u *InspectRuleUpdateOne) SetName(v string) *InspectRuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *InspectRuleUpdateOne) SetNillableName(v *string) *InspectRuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetInterval sets the "interval" field.
func (_u *InspectRuleUpdateOne) SetInterval(v string) *InspectRuleUpdateOne {
	_u.mutation.SetInterval(v)
	return _u
}

// SetNillableInterval sets the "interval" field if the given value is not nil.
func (_u *InspectRuleUpdateOne) SetNillableInterval(v *string) *InspectRuleUpdateOne {
	if v != nil {
		_u.SetInterval(*v)
	}
	return _u
}

// SetMetricQuery sets the "metric_query" field.
func (_u *InspectRuleUpdateOne) SetMetricQuery(v string) *InspectRuleUpdateOne {
	_u.mutation.SetMetricQuery(v)
	return _u
}

// SetNillableMetricQuery sets the "metric_query" field if the given value is not nil.
func (_u *InspectRuleUpdateOne) SetNillableMetricQuery(v *string) *InspectRuleUpdateOne {
	if v != nil {
		_u.SetMetricQuery(*v)
	}
	return _u
}

// SetLogQuery sets the "log_query" field.
func (_u *InspectRuleUpdateOne) SetLogQuery(v string) *InspectRuleUpdateOne {
	_u.mutation.SetLogQuery(v)
	return _u
}

// SetNillableLogQuery sets the "log_query" field if the given value is not nil.
func (_u *InspectRuleUpdateOne) SetNillableLogQuery(v *string) *InspectRuleUpdateOne {
	if v != nil {
		_u.SetLogQuery(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *InspectRuleUpdateOne) SetEnabled(v bool) *InspectRuleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *InspectRuleUpdateOne) SetNillableEnabled(v *bool) *InspectRuleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the InspectRuleMutation object of the builder.
func (_u *InspectRuleUpdateOne) Mutation() *InspectRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the InspectRuleUpdate builder.
func (_u *InspectRuleUpdateOne) Where(ps ...predicate.InspectRule) *InspectRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InspectRuleUpdateOne) Select(field string, fields ...string) *InspectRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InspectRule entity.
func (_u *InspectRuleUpdateOne) Save(ctx context.Context) (*InspectRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InspectRuleUpdateOne) SaveX(ctx context.Context) *InspectRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InspectRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InspectRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InspectRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := inspectrule.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InspectRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := inspectrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "InspectRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Interval(); ok {
		if err := inspectrule.IntervalValidator(v); err != nil {
			return &ValidationError{Name: "interval", err: fmt.Errorf(`ent: validator failed for field "InspectRule.interval": %w`, err)}
		}
	}
	return nil
}

func (_u *InspectRuleUpdateOne) sqlSave(ctx context.Context) (_node *InspectRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(inspectrule.Table, inspectrule.Columns, sqlgraph.NewFieldSpec(inspectrule.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InspectRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, inspectrule.FieldID)
		for _, f := range fields {
			if !inspectrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != inspectrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(inspectrule.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(inspectrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Interval(); ok {
		_spec.SetField(inspectrule.FieldInterval, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetricQuery(); ok {
		_spec.SetField(inspectrule.FieldMetricQuery, field.TypeString, value)
	}
	if value, ok := _u.mutation.LogQuery(); ok {
		_spec.SetField(inspectrule.FieldLogQuery, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(inspectrule.FieldEnabled, field.TypeBool, value)
	}
	_node = &InspectRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inspectrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
