// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/serengeti-sh/meerkat/ent/inspectrule"
)

// InspectRule is the model entity for the InspectRule schema.
type InspectRule struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Interval holds the value of the "interval" field.
	Interval string `json:"interval,omitempty"`
	// MetricQuery holds the value of the "metric_query" field.
	MetricQuery string `json:"metric_query,omitempty"`
	// LogQuery holds the value of the "log_query" field.
	LogQuery string `json:"log_query,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled      bool `json:"enabled,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InspectRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case inspectrule.FieldEnabled:
			values[i] = new(sql.NullBool)
		case inspectrule.FieldID, inspectrule.FieldName, inspectrule.FieldInterval, inspectrule.FieldMetricQuery, inspectrule.FieldLogQuery:
			values[i] = new(sql.NullString)
		case inspectrule.FieldCreateTime, inspectrule.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InspectRule fields.
func (_m *InspectRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case inspectrule.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case inspectrule.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case inspectrule.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case inspectrule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case inspectrule.FieldInterval:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field interval", values[i])
			} else if value.Valid {
				_m.Interval = value.String
			}
		case inspectrule.FieldMetricQuery:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metric_query", values[i])
			} else if value.Valid {
				_m.MetricQuery = value.String
			}
		case inspectrule.FieldLogQuery:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field log_query", values[i])
			} else if value.Valid {
				_m.LogQuery = value.String
			}
		case inspectrule.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InspectRule.
// This includes values selected through modifiers, order, etc.
func (_m *InspectRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this InspectRule.
// Note that you need to call InspectRule.Unwrap() before calling this method if this InspectRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InspectRule) Update() *InspectRuleUpdateOne {
	return NewInspectRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InspectRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InspectRule) Unwrap() *InspectRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InspectRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InspectRule) String() string {
	var builder strings.Builder
	builder.WriteString("InspectRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("interval=")
	builder.WriteString(_m.Interval)
	builder.WriteString(", ")
	builder.WriteString("metric_query=")
	builder.WriteString(_m.MetricQuery)
	builder.WriteString(", ")
	builder.WriteString("log_query=")
	builder.WriteString(_m.LogQuery)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// InspectRules is a parsable slice of InspectRule.
type InspectRules []*InspectRule
