// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mandacode-labs/inspector/ent/inspectrule"
	"github.com/mandacode-labs/inspector/ent/predicate"
	"github.com/mandacode-labs/inspector/ent/report"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeInspectRule = "InspectRule"
	TypeReport      = "Report"
)

// InspectRuleMutation represents an operation that mutates the InspectRule nodes in the graph.
type InspectRuleMutation struct {
	config
	op            Op
	typ           string
	id            *string
	create_time   *time.Time
	update_time   *time.Time
	name          *string
	interval      *string
	metric_query  *string
	log_query     *string
	enabled       *bool
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*InspectRule, error)
	predicates    []predicate.InspectRule
}

var _ ent.Mutation = (*InspectRuleMutation)(nil)

// inspectruleOption allows management of the mutation configuration using functional options.
type inspectruleOption func(*InspectRuleMutation)

// newInspectRuleMutation creates new mutation for the InspectRule entity.
func newInspectRuleMutation(c config, op Op, opts ...inspectruleOption) *InspectRuleMutation {
	m := &InspectRuleMutation{
		config:        c,
		op:            op,
		typ:           TypeInspectRule,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withInspectRuleID sets the ID field of the mutation.
func withInspectRuleID(id string) inspectruleOption {
	return func(m *InspectRuleMutation) {
		var (
			err   error
			once  sync.Once
			value *InspectRule
		)
		m.oldValue = func(ctx context.Context) (*InspectRule, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().InspectRule.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withInspectRule sets the old InspectRule of the mutation.
func withInspectRule(node *InspectRule) inspectruleOption {
	return func(m *InspectRuleMutation) {
		m.oldValue = func(context.Context) (*InspectRule, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m InspectRuleMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m InspectRuleMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of InspectRule entities.
func (m *InspectRuleMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *InspectRuleMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *InspectRuleMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().InspectRule.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreateTime sets the "create_time" field.
func (m *InspectRuleMutation) SetCreateTime(t time.Time) {
	m.create_time = &t
}

// CreateTime returns the value of the "create_time" field in the mutation.
func (m *InspectRuleMutation) CreateTime() (r time.Time, exists bool) {
	v := m.create_time
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateTime returns the old "create_time" field's value of the InspectRule entity.
// If the InspectRule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InspectRuleMutation) OldCreateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateTime: %w", err)
	}
	return oldValue.CreateTime, nil
}

// ResetCreateTime resets all changes to the "create_time" field.
func (m *InspectRuleMutation) ResetCreateTime() {
	m.create_time = nil
}

// SetUpdateTime sets the "update_time" field.
func (m *InspectRuleMutation) SetUpdateTime(t time.Time) {
	m.update_time = &t
}

// UpdateTime returns the value of the "update_time" field in the mutation.
func (m *InspectRuleMutation) UpdateTime() (r time.Time, exists bool) {
	v := m.update_time
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateTime returns the old "update_time" field's value of the InspectRule entity.
// If the InspectRule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InspectRuleMutation) OldUpdateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateTime: %w", err)
	}
	return oldValue.UpdateTime, nil
}

// ResetUpdateTime resets all changes to the "update_time" field.
func (m *InspectRuleMutation) ResetUpdateTime() {
	m.update_time = nil
}

// SetName sets the "name" field.
func (m *InspectRuleMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *InspectRuleMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the InspectRule entity.
// If the InspectRule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InspectRuleMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *InspectRuleMutation) ResetName() {
	m.name = nil
}

// SetInterval sets the "interval" field.
func (m *InspectRuleMutation) SetInterval(s string) {
	m.interval = &s
}

// Interval returns the value of the "interval" field in the mutation.
func (m *InspectRuleMutation) Interval() (r string, exists bool) {
	v := m.interval
	if v == nil {
		return
	}
	return *v, true
}

// OldInterval returns the old "interval" field's value of the InspectRule entity.
// If the InspectRule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InspectRuleMutation) OldInterval(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInterval is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInterval requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInterval: %w", err)
	}
	return oldValue.Interval, nil
}

// ResetInterval resets all changes to the "interval" field.
func (m *InspectRuleMutation) ResetInterval() {
	m.interval = nil
}

// SetMetricQuery sets the "metric_query" field.
func (m *InspectRuleMutation) SetMetricQuery(s string) {
	m.metric_query = &s
}

// MetricQuery returns the value of the "metric_query" field in the mutation.
func (m *InspectRuleMutation) MetricQuery() (r string, exists bool) {
	v := m.metric_query
	if v == nil {
		return
	}
	return *v, true
}

// OldMetricQuery returns the old "metric_query" field's value of the InspectRule entity.
// If the InspectRule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InspectRuleMutation) OldMetricQuery(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMetricQuery is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMetricQuery requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMetricQuery: %w", err)
	}
	return oldValue.MetricQuery, nil
}

// ResetMetricQuery resets all changes to the "metric_query" field.
func (m *InspectRuleMutation) ResetMetricQuery() {
	m.metric_query = nil
}

// SetLogQuery sets the "log_query" field.
func (m *InspectRuleMutation) SetLogQuery(s string) {
	m.log_query = &s
}

// LogQuery returns the value of the "log_query" field in the mutation.
func (m *InspectRuleMutation) LogQuery() (r string, exists bool) {
	v := m.log_query
	if v == nil {
		return
	}
	return *v, true
}

// OldLogQuery returns the old "log_query" field's value of the InspectRule entity.
// If the InspectRule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InspectRuleMutation) OldLogQuery(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLogQuery is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLogQuery requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLogQuery: %w", err)
	}
	return oldValue.LogQuery, nil
}

// ResetLogQuery resets all changes to the "log_query" field.
func (m *InspectRuleMutation) ResetLogQuery() {
	m.log_query = nil
}

// SetEnabled sets the "enabled" field.
func (m *InspectRuleMutation) SetEnabled(b bool) {
	m.enabled = &b
}

// Enabled returns the value of the "enabled" field in the mutation.
func (m *InspectRuleMutation) Enabled() (r bool, exists bool) {
	v := m.enabled
	if v == nil {
		return
	}
	return *v, true
}

// OldEnabled returns the old "enabled" field's value of the InspectRule entity.
// If the InspectRule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InspectRuleMutation) OldEnabled(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnabled is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnabled requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnabled: %w", err)
	}
	return oldValue.Enabled, nil
}

// ResetEnabled resets all changes to the "enabled" field.
func (m *InspectRuleMutation) ResetEnabled() {
	m.enabled = nil
}

// Where appends a list predicates to the InspectRuleMutation builder.
func (m *InspectRuleMutation) Where(ps ...predicate.InspectRule) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the InspectRuleMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *InspectRuleMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.InspectRule, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *InspectRuleMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *InspectRuleMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (InspectRule).
func (m *InspectRuleMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *InspectRuleMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.create_time != nil {
		fields = append(fields, inspectrule.FieldCreateTime)
	}
	if m.update_time != nil {
		fields = append(fields, inspectrule.FieldUpdateTime)
	}
	if m.name != nil {
		fields = append(fields, inspectrule.FieldName)
	}
	if m.interval != nil {
		fields = append(fields, inspectrule.FieldInterval)
	}
	if m.metric_query != nil {
		fields = append(fields, inspectrule.FieldMetricQuery)
	}
	if m.log_query != nil {
		fields = append(fields, inspectrule.FieldLogQuery)
	}
	if m.enabled != nil {
		fields = append(fields, inspectrule.FieldEnabled)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *InspectRuleMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case inspectrule.FieldCreateTime:
		return m.CreateTime()
	case inspectrule.FieldUpdateTime:
		return m.UpdateTime()
	case inspectrule.FieldName:
		return m.Name()
	case inspectrule.FieldInterval:
		return m.Interval()
	case inspectrule.FieldMetricQuery:
		return m.MetricQuery()
	case inspectrule.FieldLogQuery:
		return m.LogQuery()
	case inspectrule.FieldEnabled:
		return m.Enabled()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *InspectRuleMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case inspectrule.FieldCreateTime:
		return m.OldCreateTime(ctx)
	case inspectrule.FieldUpdateTime:
		return m.OldUpdateTime(ctx)
	case inspectrule.FieldName:
		return m.OldName(ctx)
	case inspectrule.FieldInterval:
		return m.OldInterval(ctx)
	case inspectrule.FieldMetricQuery:
		return m.OldMetricQuery(ctx)
	case inspectrule.FieldLogQuery:
		return m.OldLogQuery(ctx)
	case inspectrule.FieldEnabled:
		return m.OldEnabled(ctx)
	}
	return nil, fmt.Errorf("unknown InspectRule field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *InspectRuleMutation) SetField(name string, value ent.Value) error {
	switch name {
	case inspectrule.FieldCreateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateTime(v)
		return nil
	case inspectrule.FieldUpdateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateTime(v)
		return nil
	case inspectrule.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case inspectrule.FieldInterval:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInterval(v)
		return nil
	case inspectrule.FieldMetricQuery:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMetricQuery(v)
		return nil
	case inspectrule.FieldLogQuery:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLogQuery(v)
		return nil
	case inspectrule.FieldEnabled:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnabled(v)
		return nil
	}
	return fmt.Errorf("unknown InspectRule field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *InspectRuleMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *InspectRuleMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *InspectRuleMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown InspectRule numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *InspectRuleMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *InspectRuleMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *InspectRuleMutation) ClearField(name string) error {
	return fmt.Errorf("unknown InspectRule nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *InspectRuleMutation) ResetField(name string) error {
	switch name {
	case inspectrule.FieldCreateTime:
		m.ResetCreateTime()
		return nil
	case inspectrule.FieldUpdateTime:
		m.ResetUpdateTime()
		return nil
	case inspectrule.FieldName:
		m.ResetName()
		return nil
	case inspectrule.FieldInterval:
		m.ResetInterval()
		return nil
	case inspectrule.FieldMetricQuery:
		m.ResetMetricQuery()
		return nil
	case inspectrule.FieldLogQuery:
		m.ResetLogQuery()
		return nil
	case inspectrule.FieldEnabled:
		m.ResetEnabled()
		return nil
	}
	return fmt.Errorf("unknown InspectRule field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *InspectRuleMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *InspectRuleMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *InspectRuleMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *InspectRuleMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *InspectRuleMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *InspectRuleMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *InspectRuleMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown InspectRule unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *InspectRuleMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown InspectRule edge %s", name)
}

// ReportMutation represents an operation that mutates the Report nodes in the graph.
type ReportMutation struct {
	config
	op                Op
	typ               string
	id                *string
	create_time       *time.Time
	update_time       *time.Time
	trigger           *report.Trigger
	trigger_id        *string
	status            *report.Status
	severity          *report.Severity
	summary           *string
	detail            *string
	query             *string
	datasources       *[]string
	appenddatasources []string
	iterations        *int
	additerations     *int
	clearedFields     map[string]struct{}
	done              bool
	oldValue          func(context.Context) (*Report, error)
	predicates        []predicate.Report
}

var _ ent.Mutation = (*ReportMutation)(nil)

// reportOption allows management of the mutation configuration using functional options.
type reportOption func(*ReportMutation)

// newReportMutation creates new mutation for the Report entity.
func newReportMutation(c config, op Op, opts ...reportOption) *ReportMutation {
	m := &ReportMutation{
		config:        c,
		op:            op,
		typ:           TypeReport,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withReportID sets the ID field of the mutation.
func withReportID(id string) reportOption {
	return func(m *ReportMutation) {
		var (
			err   error
			once  sync.Once
			value *Report
		)
		m.oldValue = func(ctx context.Context) (*Report, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Report.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withReport sets the old Report of the mutation.
func withReport(node *Report) reportOption {
	return func(m *ReportMutation) {
		m.oldValue = func(context.Context) (*Report, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ReportMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ReportMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Report entities.
func (m *ReportMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ReportMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ReportMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Report.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreateTime sets the "create_time" field.
func (m *ReportMutation) SetCreateTime(t time.Time) {
	m.create_time = &t
}

// CreateTime returns the value of the "create_time" field in the mutation.
func (m *ReportMutation) CreateTime() (r time.Time, exists bool) {
	v := m.create_time
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateTime returns the old "create_time" field's value of the Report entity.
// If the Report object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReportMutation) OldCreateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateTime: %w", err)
	}
	return oldValue.CreateTime, nil
}

// ResetCreateTime resets all changes to the "create_time" field.
func (m *ReportMutation) ResetCreateTime() {
	m.create_time = nil
}

// SetUpdateTime sets the "update_time" field.
func (m *ReportMutation) SetUpdateTime(t time.Time) {
	m.update_time = &t
}

// UpdateTime returns the value of the "update_time" field in the mutation.
func (m *ReportMutation) UpdateTime() (r time.Time, exists bool) {
	v := m.update_time
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateTime returns the old "update_time" field's value of the Report entity.
// If the Report object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReportMutation) OldUpdateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateTime: %w", err)
	}
	return oldValue.UpdateTime, nil
}

// ResetUpdateTime resets all changes to the "update_time" field.
func (m *ReportMutation) ResetUpdateTime() {
	m.update_time = nil
}

// SetTrigger sets the "trigger" field.
func (m *ReportMutation) SetTrigger(r report.Trigger) {
	m.trigger = &r
}

// Trigger returns the value of the "trigger" field in the mutation.
func (m *ReportMutation) Trigger() (r report.Trigger, exists bool) {
	v := m.trigger
	if v == nil {
		return
	}
	return *v, true
}

// OldTrigger returns the old "trigger" field's value of the Report entity.
// If the Report object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReportMutation) OldTrigger(ctx context.Context) (v report.Trigger, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTrigger is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTrigger requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTrigger: %w", err)
	}
	return oldValue.Trigger, nil
}

// ResetTrigger resets all changes to the "trigger" field.
func (m *ReportMutation) ResetTrigger() {
	m.trigger = nil
}

// SetTriggerID sets the "trigger_id" field.
func (m *ReportMutation) SetTriggerID(s string) {
	m.trigger_id = &s
}

// TriggerID returns the value of the "trigger_id" field in the mutation.
func (m *ReportMutation) TriggerID() (r string, exists bool) {
	v := m.trigger_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTriggerID returns the old "trigger_id" field's value of the Report entity.
// If the Report object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReportMutation) OldTriggerID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTriggerID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTriggerID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTriggerID: %w", err)
	}
	return oldValue.TriggerID, nil
}

// ResetTriggerID resets all changes to the "trigger_id" field.
func (m *ReportMutation) ResetTriggerID() {
	m.trigger_id = nil
}

// SetStatus sets the "status" field.
func (m *ReportMutation) SetStatus(r report.Status) {
	m.status = &r
}

// Status returns the value of the "status" field in the mutation.
func (m *ReportMutation) Status() (r report.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Report entity.
// If the Report object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReportMutation) OldStatus(ctx context.Context) (v report.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *ReportMutation) ResetStatus() {
	m.status = nil
}

// SetSeverity sets the "severity" field.
func (m *ReportMutation) SetSeverity(r report.Severity) {
	m.severity = &r
}

// Severity returns the value of the "severity" field in the mutation.
func (m *ReportMutation) Severity() (r report.Severity, exists bool) {
	v := m.severity
	if v == nil {
		return
	}
	return *v, true
}

// OldSeverity returns the old "severity" field's value of the Report entity.
// If the Report object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReportMutation) OldSeverity(ctx context.Context) (v report.Severity, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSeverity is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSeverity requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSeverity: %w", err)
	}
	return oldValue.Severity, nil
}

// ResetSeverity resets all changes to the "severity" field.
func (m *ReportMutation) ResetSeverity() {
	m.severity = nil
}

// SetSummary sets the "summary" field.
func (m *ReportMutation) SetSummary(s string) {
	m.summary = &s
}

// Summary returns the value of the "summary" field in the mutation.
func (m *ReportMutation) Summary() (r string, exists bool) {
	v := m.summary
	if v == nil {
		return
	}
	return *v, true
}

// OldSummary returns the old "summary" field's value of the Report entity.
// If the Report object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReportMutation) OldSummary(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSummary is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSummary requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSummary: %w", err)
	}
	return oldValue.Summary, nil
}

// ResetSummary resets all changes to the "summary" field.
func (m *ReportMutation) ResetSummary() {
	m.summary = nil
}

// SetDetail sets the "detail" field.
func (m *ReportMutation) SetDetail(s string) {
	m.detail = &s
}

// Detail returns the value of the "detail" field in the mutation.
func (m *ReportMutation) Detail() (r string, exists bool) {
	v := m.detail
	if v == nil {
		return
	}
	return *v, true
}

// OldDetail returns the old "detail" field's value of the Report entity.
// If the Report object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReportMutation) OldDetail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDetail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDetail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDetail: %w", err)
	}
	return oldValue.Detail, nil
}

// ResetDetail resets all changes to the "detail" field.
func (m *ReportMutation) ResetDetail() {
	m.detail = nil
}

// SetQuery sets the "query" field.
func (m *ReportMutation) SetQuery(s string) {
	m.query = &s
}

// Query returns the value of the "query" field in the mutation.
func (m *ReportMutation) Query() (r string, exists bool) {
	v := m.query
	if v == nil {
		return
	}
	return *v, true
}

// OldQuery returns the old "query" field's value of the Report entity.
// If the Report object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReportMutation) OldQuery(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldQuery is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldQuery requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldQuery: %w", err)
	}
	return oldValue.Query, nil
}

// ClearQuery clears the value of the "query" field.
func (m *ReportMutation) ClearQuery() {
	m.query = nil
	m.clearedFields[report.FieldQuery] = struct{}{}
}

// QueryCleared returns if the "query" field was cleared in this mutation.
func (m *ReportMutation) QueryCleared() bool {
	_, ok := m.clearedFields[report.FieldQuery]
	return ok
}

// ResetQuery resets all changes to the "query" field.
func (m *ReportMutation) ResetQuery() {
	m.query = nil
	delete(m.clearedFields, report.FieldQuery)
}

// SetDatasources sets the "datasources" field.
func (m *ReportMutation) SetDatasources(s []string) {
	m.datasources = &s
	m.appenddatasources = nil
}

// Datasources returns the value of the "datasources" field in the mutation.
func (m *ReportMutation) Datasources() (r []string, exists bool) {
	v := m.datasources
	if v == nil {
		return
	}
	return *v, true
}

// OldDatasources returns the old "datasources" field's value of the Report entity.
// If the Report object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReportMutation) OldDatasources(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDatasources is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDatasources requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDatasources: %w", err)
	}
	return oldValue.Datasources, nil
}

// AppendDatasources adds s to the "datasources" field.
func (m *ReportMutation) AppendDatasources(s []string) {
	m.appenddatasources = append(m.appenddatasources, s...)
}

// AppendedDatasources returns the list of values that were appended to the "datasources" field in this mutation.
func (m *ReportMutation) AppendedDatasources() ([]string, bool) {
	if len(m.appenddatasources) == 0 {
		return nil, false
	}
	return m.appenddatasources, true
}

// ResetDatasources resets all changes to the "datasources" field.
func (m *ReportMutation) ResetDatasources() {
	m.datasources = nil
	m.appenddatasources = nil
}

// SetIterations sets the "iterations" field.
func (m *ReportMutation) SetIterations(i int) {
	m.iterations = &i
	m.additerations = nil
}

// Iterations returns the value of the "iterations" field in the mutation.
func (m *ReportMutation) Iterations() (r int, exists bool) {
	v := m.iterations
	if v == nil {
		return
	}
	return *v, true
}

// OldIterations returns the old "iterations" field's value of the Report entity.
// If the Report object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReportMutation) OldIterations(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIterations is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIterations requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIterations: %w", err)
	}
	return oldValue.Iterations, nil
}

// AddIterations adds i to the "iterations" field.
func (m *ReportMutation) AddIterations(i int) {
	if m.additerations != nil {
		*m.additerations += i
	} else {
		m.additerations = &i
	}
}

// AddedIterations returns the value that was added to the "iterations" field in this mutation.
func (m *ReportMutation) AddedIterations() (r int, exists bool) {
	v := m.additerations
	if v == nil {
		return
	}
	return *v, true
}

// ResetIterations resets all changes to the "iterations" field.
func (m *ReportMutation) ResetIterations() {
	m.iterations = nil
	m.additerations = nil
}

// Where appends a list predicates to the ReportMutation builder.
func (m *ReportMutation) Where(ps ...predicate.Report) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ReportMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ReportMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Report, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ReportMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ReportMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Report).
func (m *ReportMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ReportMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.create_time != nil {
		fields = append(fields, report.FieldCreateTime)
	}
	if m.update_time != nil {
		fields = append(fields, report.FieldUpdateTime)
	}
	if m.trigger != nil {
		fields = append(fields, report.FieldTrigger)
	}
	if m.trigger_id != nil {
		fields = append(fields, report.FieldTriggerID)
	}
	if m.status != nil {
		fields = append(fields, report.FieldStatus)
	}
	if m.severity != nil {
		fields = append(fields, report.FieldSeverity)
	}
	if m.summary != nil {
		fields = append(fields, report.FieldSummary)
	}
	if m.detail != nil {
		fields = append(fields, report.FieldDetail)
	}
	if m.query != nil {
		fields = append(fields, report.FieldQuery)
	}
	if m.datasources != nil {
		fields = append(fields, report.FieldDatasources)
	}
	if m.iterations != nil {
		fields = append(fields, report.FieldIterations)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ReportMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case report.FieldCreateTime:
		return m.CreateTime()
	case report.FieldUpdateTime:
		return m.UpdateTime()
	case report.FieldTrigger:
		return m.Trigger()
	case report.FieldTriggerID:
		return m.TriggerID()
	case report.FieldStatus:
		return m.Status()
	case report.FieldSeverity:
		return m.Severity()
	case report.FieldSummary:
		return m.Summary()
	case report.FieldDetail:
		return m.Detail()
	case report.FieldQuery:
		return m.Query()
	case report.FieldDatasources:
		return m.Datasources()
	case report.FieldIterations:
		return m.Iterations()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ReportMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case report.FieldCreateTime:
		return m.OldCreateTime(ctx)
	case report.FieldUpdateTime:
		return m.OldUpdateTime(ctx)
	case report.FieldTrigger:
		return m.OldTrigger(ctx)
	case report.FieldTriggerID:
		return m.OldTriggerID(ctx)
	case report.FieldStatus:
		return m.OldStatus(ctx)
	case report.FieldSeverity:
		return m.OldSeverity(ctx)
	case report.FieldSummary:
		return m.OldSummary(ctx)
	case report.FieldDetail:
		return m.OldDetail(ctx)
	case report.FieldQuery:
		return m.OldQuery(ctx)
	case report.FieldDatasources:
		return m.OldDatasources(ctx)
	case report.FieldIterations:
		return m.OldIterations(ctx)
	}
	return nil, fmt.Errorf("unknown Report field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ReportMutation) SetField(name string, value ent.Value) error {
	switch name {
	case report.FieldCreateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateTime(v)
		return nil
	case report.FieldUpdateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateTime(v)
		return nil
	case report.FieldTrigger:
		v, ok := value.(report.Trigger)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTrigger(v)
		return nil
	case report.FieldTriggerID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTriggerID(v)
		return nil
	case report.FieldStatus:
		v, ok := value.(report.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case report.FieldSeverity:
		v, ok := value.(report.Severity)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSeverity(v)
		return nil
	case report.FieldSummary:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSummary(v)
		return nil
	case report.FieldDetail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDetail(v)
		return nil
	case report.FieldQuery:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetQuery(v)
		return nil
	case report.FieldDatasources:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDatasources(v)
		return nil
	case report.FieldIterations:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIterations(v)
		return nil
	}
	return fmt.Errorf("unknown Report field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ReportMutation) AddedFields() []string {
	var fields []string
	if m.additerations != nil {
		fields = append(fields, report.FieldIterations)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ReportMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case report.FieldIterations:
		return m.AddedIterations()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ReportMutation) AddField(name string, value ent.Value) error {
	switch name {
	case report.FieldIterations:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddIterations(v)
		return nil
	}
	return fmt.Errorf("unknown Report numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ReportMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(report.FieldQuery) {
		fields = append(fields, report.FieldQuery)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ReportMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ReportMutation) ClearField(name string) error {
	switch name {
	case report.FieldQuery:
		m.ClearQuery()
		return nil
	}
	return fmt.Errorf("unknown Report nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ReportMutation) ResetField(name string) error {
	switch name {
	case report.FieldCreateTime:
		m.ResetCreateTime()
		return nil
	case report.FieldUpdateTime:
		m.ResetUpdateTime()
		return nil
	case report.FieldTrigger:
		m.ResetTrigger()
		return nil
	case report.FieldTriggerID:
		m.ResetTriggerID()
		return nil
	case report.FieldStatus:
		m.ResetStatus()
		return nil
	case report.FieldSeverity:
		m.ResetSeverity()
		return nil
	case report.FieldSummary:
		m.ResetSummary()
		return nil
	case report.FieldDetail:
		m.ResetDetail()
		return nil
	case report.FieldQuery:
		m.ResetQuery()
		return nil
	case report.FieldDatasources:
		m.ResetDatasources()
		return nil
	case report.FieldIterations:
		m.ResetIterations()
		return nil
	}
	return fmt.Errorf("unknown Report field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ReportMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ReportMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ReportMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ReportMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ReportMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ReportMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ReportMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Report unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ReportMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Report edge %s", name)
}
