// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mandacode-labs/inspector/ent/report"
)

// ReportCreate is the builder for creating a Report entity.
type ReportCreate struct {
	config
	mutation *ReportMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *ReportCreate) SetCreateTime(v time.Time) *ReportCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *ReportCreate) SetNillableCreateTime(v *time.Time) *ReportCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *ReportCreate) SetUpdateTime(v time.Time) *ReportCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *ReportCreate) SetNillableUpdateTime(v *time.Time) *ReportCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetTrigger sets the "trigger" field.
func (_c *ReportCreate) SetTrigger(v report.Trigger) *ReportCreate {
	_c.mutation.SetTrigger(v)
	return _c
}

// SetTriggerID sets the "trigger_id" field.
func (_c *ReportCreate) SetTriggerID(v string) *ReportCreate {
	_c.mutation.SetTriggerID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ReportCreate) SetStatus(v report.Status) *ReportCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ReportCreate) SetNillableStatus(v *report.Status) *ReportCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSeverity sets the "severity" field.
func (_c *ReportCreate) SetSeverity(v report.Severity) *ReportCreate {
	_c.mutation.SetSeverity(v)
	return _c
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_c *ReportCreate) SetNillableSeverity(v *report.Severity) *ReportCreate {
	if v != nil {
		_c.SetSeverity(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *ReportCreate) SetSummary(v string) *ReportCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *ReportCreate) SetNillableSummary(v *string) *ReportCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetDetail sets the "detail" field.
func (_c *ReportCreate) SetDetail(v string) *ReportCreate {
	_c.mutation.SetDetail(v)
	return _c
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_c *ReportCreate) SetNillableDetail(v *string) *ReportCreate {
	if v != nil {
		_c.SetDetail(*v)
	}
	return _c
}

// SetQuery sets the "query" field.
func (_c *ReportCreate) SetQuery(v string) *ReportCreate {
	_c.mutation.SetQuery(v)
	return _c
}

// SetNillableQuery sets the "query" field if the given value is not nil.
func (_c *ReportCreate) SetNillableQuery(v *string) *ReportCreate {
	if v != nil {
		_c.SetQuery(*v)
	}
	return _c
}

// SetDatasources sets the "datasources" field.
func (_c *ReportCreate) SetDatasources(v []string) *ReportCreate {
	_c.mutation.SetDatasources(v)
	return _c
}

// SetIterations sets the "iterations" field.
func (_c *ReportCreate) SetIterations(v int) *ReportCreate {
	_c.mutation.SetIterations(v)
	return _c
}

// SetNillableIterations sets the "iterations" field if the given value is not nil.
func (_c *ReportCreate) SetNillableIterations(v *int) *ReportCreate {
	if v != nil {
		_c.SetIterations(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ReportCreate) SetID(v string) *ReportCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ReportMutation object of the builder.
func (_c *ReportCreate) Mutation() *ReportMutation {
	return _c.mutation
}

// Save creates the Report in the database.
func (_c *ReportCreate) Save(ctx context.Context) (*Report, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReportCreate) SaveX(ctx context.Context) *Report {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReportCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := report.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := report.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := report.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Severity(); !ok {
		v := report.DefaultSeverity
		_c.mutation.SetSeverity(v)
	}
	if _, ok := _c.mutation.Summary(); !ok {
		v := report.DefaultSummary
		_c.mutation.SetSummary(v)
	}
	if _, ok := _c.mutation.Detail(); !ok {
		v := report.DefaultDetail
		_c.mutation.SetDetail(v)
	}
	if _, ok := _c.mutation.Query(); !ok {
		v := report.DefaultQuery
		_c.mutation.SetQuery(v)
	}
	if _, ok := _c.mutation.Iterations(); !ok {
		v := report.DefaultIterations
		_c.mutation.SetIterations(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReportCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Report.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Report.update_time"`)}
	}
	if _, ok := _c.mutation.Trigger(); !ok {
		return &ValidationError{Name: "trigger", err: errors.New(`ent: missing required field "Report.trigger"`)}
	}
	if v, ok := _c.mutation.Trigger(); ok {
		if err := report.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "Report.trigger": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TriggerID(); !ok {
		return &ValidationError{Name: "trigger_id", err: errors.New(`ent: missing required field "Report.trigger_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Report.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := report.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Report.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Severity(); !ok {
		return &ValidationError{Name: "severity", err: errors.New(`ent: missing required field "Report.severity"`)}
	}
	if v, ok := _c.mutation.Severity(); ok {
		if err := report.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "Report.severity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "Report.summary"`)}
	}
	if _, ok := _c.mutation.Detail(); !ok {
		return &ValidationError{Name: "detail", err: errors.New(`ent: missing required field "Report.detail"`)}
	}
	if _, ok := _c.mutation.Datasources(); !ok {
		return &ValidationError{Name: "datasources", err: errors.New(`ent: missing required field "Report.datasources"`)}
	}
	if _, ok := _c.mutation.Iterations(); !ok {
		return &ValidationError{Name: "iterations", err: errors.New(`ent: missing required field "Report.iterations"`)}
	}
	return nil
}

func (_c *ReportCreate) sqlSave(ctx context.Context) (*Report, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Report.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReportCreate) createSpec() (*Report, *sqlgraph.CreateSpec) {
	var (
		_node = &Report{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(report.Table, sqlgraph.NewFieldSpec(report.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(report.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(report.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Trigger(); ok {
		_spec.SetField(report.FieldTrigger, field.TypeEnum, value)
		_node.Trigger = value
	}
	if value, ok := _c.mutation.TriggerID(); ok {
		_spec.SetField(report.FieldTriggerID, field.TypeString, value)
		_node.TriggerID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Severity(); ok {
		_spec.SetField(report.FieldSeverity, field.TypeEnum, value)
		_node.Severity = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(report.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Detail(); ok {
		_spec.SetField(report.FieldDetail, field.TypeString, value)
		_node.Detail = value
	}
	if value, ok := _c.mutation.Query(); ok {
		_spec.SetField(report.FieldQuery, field.TypeString, value)
		_node.Query = value
	}
	if value, ok := _c.mutation.Datasources(); ok {
		_spec.SetField(report.FieldDatasources, field.TypeJSON, value)
		_node.Datasources = value
	}
	if value, ok := _c.mutation.Iterations(); ok {
		_spec.SetField(report.FieldIterations, field.TypeInt, value)
		_node.Iterations = value
	}
	return _node, _spec
}

// ReportCreateBulk is the builder for creating many Report entities in bulk.
type ReportCreateBulk struct {
	config
	err      error
	builders []*ReportCreate
}

// Save creates the Report entities in the database.
func (_c *ReportCreateBulk) Save(ctx context.Context) ([]*Report, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Report, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReportCreateBulk) SaveX(ctx context.Context) []*Report {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
