// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/serengeti-sh/meerkat/ent/report"
)

// Report is the model entity for the Report schema.
type Report struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Trigger holds the value of the "trigger" field.
	Trigger report.Trigger `json:"trigger,omitempty"`
	// TriggerID holds the value of the "trigger_id" field.
	TriggerID string `json:"trigger_id,omitempty"`
	// Status holds the value of the "status" field.
	Status report.Status `json:"status,omitempty"`
	// Severity holds the value of the "severity" field.
	Severity report.Severity `json:"severity,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// Detail holds the value of the "detail" field.
	Detail string `json:"detail,omitempty"`
	// Query holds the value of the "query" field.
	Query string `json:"query,omitempty"`
	// Datasources holds the value of the "datasources" field.
	Datasources []string `json:"datasources,omitempty"`
	// Iterations holds the value of the "iterations" field.
	Iterations   int `json:"iterations,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Report) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case report.FieldDatasources:
			values[i] = new([]byte)
		case report.FieldIterations:
			values[i] = new(sql.NullInt64)
		case report.FieldID, report.FieldTrigger, report.FieldTriggerID, report.FieldStatus, report.FieldSeverity, report.FieldSummary, report.FieldDetail, report.FieldQuery:
			values[i] = new(sql.NullString)
		case report.FieldCreateTime, report.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Report fields.
func (_m *Report) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case report.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case report.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case report.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case report.FieldTrigger:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger", values[i])
			} else if value.Valid {
				_m.Trigger = report.Trigger(value.String)
			}
		case report.FieldTriggerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_id", values[i])
			} else if value.Valid {
				_m.TriggerID = value.String
			}
		case report.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = report.Status(value.String)
			}
		case report.FieldSeverity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field severity", values[i])
			} else if value.Valid {
				_m.Severity = report.Severity(value.String)
			}
		case report.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case report.FieldDetail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field detail", values[i])
			} else if value.Valid {
				_m.Detail = value.String
			}
		case report.FieldQuery:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field query", values[i])
			} else if value.Valid {
				_m.Query = value.String
			}
		case report.FieldDatasources:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field datasources", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Datasources); err != nil {
					return fmt.Errorf("unmarshal field datasources: %w", err)
				}
			}
		case report.FieldIterations:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field iterations", values[i])
			} else if value.Valid {
				_m.Iterations = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Report.
// This includes values selected through modifiers, order, etc.
func (_m *Report) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Report.
// Note that you need to call Report.Unwrap() before calling this method if this Report
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Report) Update() *ReportUpdateOne {
	return NewReportClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Report entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Report) Unwrap() *Report {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Report is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Report) String() string {
	var builder strings.Builder
	builder.WriteString("Report(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("trigger=")
	builder.WriteString(fmt.Sprintf("%v", _m.Trigger))
	builder.WriteString(", ")
	builder.WriteString("trigger_id=")
	builder.WriteString(_m.TriggerID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("severity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Severity))
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("detail=")
	builder.WriteString(_m.Detail)
	builder.WriteString(", ")
	builder.WriteString("query=")
	builder.WriteString(_m.Query)
	builder.WriteString(", ")
	builder.WriteString("datasources=")
	builder.WriteString(fmt.Sprintf("%v", _m.Datasources))
	builder.WriteString(", ")
	builder.WriteString("iterations=")
	builder.WriteString(fmt.Sprintf("%v", _m.Iterations))
	builder.WriteByte(')')
	return builder.String()
}

// Reports is a parsable slice of Report.
type Reports []*Report
