// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package embeddermocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewEmbedderMock creates a new instance of EmbedderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmbedderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmbedderMock {
	mock := &EmbedderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EmbedderMock is an autogenerated mock type for the Embedder type
type EmbedderMock struct {
	mock.Mock
}

type EmbedderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *EmbedderMock) EXPECT() *EmbedderMock_Expecter {
	return &EmbedderMock_Expecter{mock: &_m.Mock}
}

// Embed provides a mock function for the type EmbedderMock
func (_mock *EmbedderMock) Embed(ctx context.Context, texts []string) ([][]float32, error) {
	ret := _mock.Called(ctx, texts)

	if len(ret) == 0 {
		panic("no return value specified for Embed")
	}

	var r0 [][]float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([][]float32, error)); ok {
		return returnFunc(ctx, texts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) [][]float32); ok {
		r0 = returnFunc(ctx, texts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, texts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EmbedderMock_Embed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Embed'
type EmbedderMock_Embed_Call struct {
	*mock.Call
}

// Embed is a helper method to define mock.On call
//   - ctx context.Context
//   - texts []string
func (_e *EmbedderMock_Expecter) Embed(ctx interface{}, texts interface{}) *EmbedderMock_Embed_Call {
	return &EmbedderMock_Embed_Call{Call: _e.mock.On("Embed", ctx, texts)}
}

func (_c *EmbedderMock_Embed_Call) Run(run func(ctx context.Context, texts []string)) *EmbedderMock_Embed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EmbedderMock_Embed_Call) Return(float32ss [][]float32, err error) *EmbedderMock_Embed_Call {
	_c.Call.Return(float32ss, err)
	return _c
}

func (_c *EmbedderMock_Embed_Call) RunAndReturn(run func(ctx context.Context, texts []string) ([][]float32, error)) *EmbedderMock_Embed_Call {
	_c.Call.Return(run)
	return _c
}
