// Code generated by ent, DO NOT EDIT.

package report

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the report type in the database.
	Label = "report"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldTrigger holds the string denoting the trigger field in the database.
	FieldTrigger = "trigger"
	// FieldTriggerID holds the string denoting the trigger_id field in the database.
	FieldTriggerID = "trigger_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSeverity holds the string denoting the severity field in the database.
	FieldSeverity = "severity"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldDetail holds the string denoting the detail field in the database.
	FieldDetail = "detail"
	// FieldQuery holds the string denoting the query field in the database.
	FieldQuery = "query"
	// FieldDatasources holds the string denoting the datasources field in the database.
	FieldDatasources = "datasources"
	// FieldIterations holds the string denoting the iterations field in the database.
	FieldIterations = "iterations"
	// Table holds the table name of the report in the database.
	Table = "reports"
)

// Columns holds all SQL columns for report fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldTrigger,
	FieldTriggerID,
	FieldStatus,
	FieldSeverity,
	FieldSummary,
	FieldDetail,
	FieldQuery,
	FieldDatasources,
	FieldIterations,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultSummary holds the default value on creation for the "summary" field.
	DefaultSummary string
	// DefaultDetail holds the default value on creation for the "detail" field.
	DefaultDetail string
	// DefaultQuery holds the default value on creation for the "query" field.
	DefaultQuery string
	// DefaultIterations holds the default value on creation for the "iterations" field.
	DefaultIterations int
)

// Trigger defines the type for the "trigger" enum field.
type Trigger string

// Trigger values.
const (
	TriggerManual    Trigger = "manual"
	TriggerWebhook   Trigger = "webhook"
	TriggerScheduled Trigger = "scheduled"
)

func (t Trigger) String() string {
	return string(t)
}

// TriggerValidator is a validator for the "trigger" field enum values. It is called by the builders before save.
func TriggerValidator(t Trigger) error {
	switch t {
	case TriggerManual, TriggerWebhook, TriggerScheduled:
		return nil
	default:
		return fmt.Errorf("report: invalid enum value for trigger field: %q", t)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusQueued is the default value of the Status enum.
const DefaultStatus = StatusQueued

// Status values.
const (
	StatusQueued    Status = "queued"
	StatusPending   Status = "pending"
	StatusRunning   Status = "running"
	StatusCompleted Status = "completed"
	StatusFailed    Status = "failed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusQueued, StatusPending, StatusRunning, StatusCompleted, StatusFailed:
		return nil
	default:
		return fmt.Errorf("report: invalid enum value for status field: %q", s)
	}
}

// Severity defines the type for the "severity" enum field.
type Severity string

// SeverityInfo is the default value of the Severity enum.
const DefaultSeverity = SeverityInfo

// Severity values.
const (
	SeverityInfo     Severity = "info"
	SeverityWarning  Severity = "warning"
	SeverityCritical Severity = "critical"
)

func (s Severity) String() string {
	return string(s)
}

// SeverityValidator is a validator for the "severity" field enum values. It is called by the builders before save.
func SeverityValidator(s Severity) error {
	switch s {
	case SeverityInfo, SeverityWarning, SeverityCritical:
		return nil
	default:
		return fmt.Errorf("report: invalid enum value for severity field: %q", s)
	}
}

// OrderOption defines the ordering options for the Report queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByTrigger orders the results by the trigger field.
func ByTrigger(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrigger, opts...).ToFunc()
}

// ByTriggerID orders the results by the trigger_id field.
func ByTriggerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySeverity orders the results by the severity field.
func BySeverity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeverity, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByDetail orders the results by the detail field.
func ByDetail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDetail, opts...).ToFunc()
}

// ByQuery orders the results by the query field.
func ByQuery(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuery, opts...).ToFunc()
}

// ByIterations orders the results by the iterations field.
func ByIterations(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIterations, opts...).ToFunc()
}
