// Code generated by ent, DO NOT EDIT.

package report

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/mandacode-labs/inspector/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Report {
	return predicate.Report(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Report {
	return predicate.Report(sql.FieldContainsFold(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldUpdateTime, v))
}

// TriggerID applies equality check predicate on the "trigger_id" field. It's identical to TriggerIDEQ.
func TriggerID(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldTriggerID, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldSummary, v))
}

// Detail applies equality check predicate on the "detail" field. It's identical to DetailEQ.
func Detail(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldDetail, v))
}

// Query applies equality check predicate on the "query" field. It's identical to QueryEQ.
func Query(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldQuery, v))
}

// Iterations applies equality check predicate on the "iterations" field. It's identical to IterationsEQ.
func Iterations(v int) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldIterations, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldUpdateTime, v))
}

// TriggerEQ applies the EQ predicate on the "trigger" field.
func TriggerEQ(v Trigger) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldTrigger, v))
}

// TriggerNEQ applies the NEQ predicate on the "trigger" field.
func TriggerNEQ(v Trigger) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldTrigger, v))
}

// TriggerIn applies the In predicate on the "trigger" field.
func TriggerIn(vs ...Trigger) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldTrigger, vs...))
}

// TriggerNotIn applies the NotIn predicate on the "trigger" field.
func TriggerNotIn(vs ...Trigger) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldTrigger, vs...))
}

// TriggerIDEQ applies the EQ predicate on the "trigger_id" field.
func TriggerIDEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldTriggerID, v))
}

// TriggerIDNEQ applies the NEQ predicate on the "trigger_id" field.
func TriggerIDNEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldTriggerID, v))
}

// TriggerIDIn applies the In predicate on the "trigger_id" field.
func TriggerIDIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldTriggerID, vs...))
}

// TriggerIDNotIn applies the NotIn predicate on the "trigger_id" field.
func TriggerIDNotIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldTriggerID, vs...))
}

// TriggerIDGT applies the GT predicate on the "trigger_id" field.
func TriggerIDGT(v string) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldTriggerID, v))
}

// TriggerIDGTE applies the GTE predicate on the "trigger_id" field.
func TriggerIDGTE(v string) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldTriggerID, v))
}

// TriggerIDLT applies the LT predicate on the "trigger_id" field.
func TriggerIDLT(v string) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldTriggerID, v))
}

// TriggerIDLTE applies the LTE predicate on the "trigger_id" field.
func TriggerIDLTE(v string) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldTriggerID, v))
}

// TriggerIDContains applies the Contains predicate on the "trigger_id" field.
func TriggerIDContains(v string) predicate.Report {
	return predicate.Report(sql.FieldContains(FieldTriggerID, v))
}

// TriggerIDHasPrefix applies the HasPrefix predicate on the "trigger_id" field.
func TriggerIDHasPrefix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasPrefix(FieldTriggerID, v))
}

// TriggerIDHasSuffix applies the HasSuffix predicate on the "trigger_id" field.
func TriggerIDHasSuffix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasSuffix(FieldTriggerID, v))
}

// TriggerIDEqualFold applies the EqualFold predicate on the "trigger_id" field.
func TriggerIDEqualFold(v string) predicate.Report {
	return predicate.Report(sql.FieldEqualFold(FieldTriggerID, v))
}

// TriggerIDContainsFold applies the ContainsFold predicate on the "trigger_id" field.
func TriggerIDContainsFold(v string) predicate.Report {
	return predicate.Report(sql.FieldContainsFold(FieldTriggerID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldStatus, vs...))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v Severity) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v Severity) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...Severity) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...Severity) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldSeverity, vs...))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.Report {
	return predicate.Report(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.Report {
	return predicate.Report(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.Report {
	return predicate.Report(sql.FieldContainsFold(FieldSummary, v))
}

// DetailEQ applies the EQ predicate on the "detail" field.
func DetailEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldDetail, v))
}

// DetailNEQ applies the NEQ predicate on the "detail" field.
func DetailNEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldDetail, v))
}

// DetailIn applies the In predicate on the "detail" field.
func DetailIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldDetail, vs...))
}

// DetailNotIn applies the NotIn predicate on the "detail" field.
func DetailNotIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldDetail, vs...))
}

// DetailGT applies the GT predicate on the "detail" field.
func DetailGT(v string) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldDetail, v))
}

// DetailGTE applies the GTE predicate on the "detail" field.
func DetailGTE(v string) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldDetail, v))
}

// DetailLT applies the LT predicate on the "detail" field.
func DetailLT(v string) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldDetail, v))
}

// DetailLTE applies the LTE predicate on the "detail" field.
func DetailLTE(v string) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldDetail, v))
}

// DetailContains applies the Contains predicate on the "detail" field.
func DetailContains(v string) predicate.Report {
	return predicate.Report(sql.FieldContains(FieldDetail, v))
}

// DetailHasPrefix applies the HasPrefix predicate on the "detail" field.
func DetailHasPrefix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasPrefix(FieldDetail, v))
}

// DetailHasSuffix applies the HasSuffix predicate on the "detail" field.
func DetailHasSuffix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasSuffix(FieldDetail, v))
}

// DetailEqualFold applies the EqualFold predicate on the "detail" field.
func DetailEqualFold(v string) predicate.Report {
	return predicate.Report(sql.FieldEqualFold(FieldDetail, v))
}

// DetailContainsFold applies the ContainsFold predicate on the "detail" field.
func DetailContainsFold(v string) predicate.Report {
	return predicate.Report(sql.FieldContainsFold(FieldDetail, v))
}

// QueryEQ applies the EQ predicate on the "query" field.
func QueryEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldQuery, v))
}

// QueryNEQ applies the NEQ predicate on the "query" field.
func QueryNEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldQuery, v))
}

// QueryIn applies the In predicate on the "query" field.
func QueryIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldQuery, vs...))
}

// QueryNotIn applies the NotIn predicate on the "query" field.
func QueryNotIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldQuery, vs...))
}

// QueryGT applies the GT predicate on the "query" field.
func QueryGT(v string) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldQuery, v))
}

// QueryGTE applies the GTE predicate on the "query" field.
func QueryGTE(v string) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldQuery, v))
}

// QueryLT applies the LT predicate on the "query" field.
func QueryLT(v string) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldQuery, v))
}

// QueryLTE applies the LTE predicate on the "query" field.
func QueryLTE(v string) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldQuery, v))
}

// QueryContains applies the Contains predicate on the "query" field.
func QueryContains(v string) predicate.Report {
	return predicate.Report(sql.FieldContains(FieldQuery, v))
}

// QueryHasPrefix applies the HasPrefix predicate on the "query" field.
func QueryHasPrefix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasPrefix(FieldQuery, v))
}

// QueryHasSuffix applies the HasSuffix predicate on the "query" field.
func QueryHasSuffix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasSuffix(FieldQuery, v))
}

// QueryIsNil applies the IsNil predicate on the "query" field.
func QueryIsNil() predicate.Report {
	return predicate.Report(sql.FieldIsNull(FieldQuery))
}

// QueryNotNil applies the NotNil predicate on the "query" field.
func QueryNotNil() predicate.Report {
	return predicate.Report(sql.FieldNotNull(FieldQuery))
}

// QueryEqualFold applies the EqualFold predicate on the "query" field.
func QueryEqualFold(v string) predicate.Report {
	return predicate.Report(sql.FieldEqualFold(FieldQuery, v))
}

// QueryContainsFold applies the ContainsFold predicate on the "query" field.
func QueryContainsFold(v string) predicate.Report {
	return predicate.Report(sql.FieldContainsFold(FieldQuery, v))
}

// IterationsEQ applies the EQ predicate on the "iterations" field.
func IterationsEQ(v int) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldIterations, v))
}

// IterationsNEQ applies the NEQ predicate on the "iterations" field.
func IterationsNEQ(v int) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldIterations, v))
}

// IterationsIn applies the In predicate on the "iterations" field.
func IterationsIn(vs ...int) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldIterations, vs...))
}

// IterationsNotIn applies the NotIn predicate on the "iterations" field.
func IterationsNotIn(vs ...int) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldIterations, vs...))
}

// IterationsGT applies the GT predicate on the "iterations" field.
func IterationsGT(v int) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldIterations, v))
}

// IterationsGTE applies the GTE predicate on the "iterations" field.
func IterationsGTE(v int) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldIterations, v))
}

// IterationsLT applies the LT predicate on the "iterations" field.
func IterationsLT(v int) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldIterations, v))
}

// IterationsLTE applies the LTE predicate on the "iterations" field.
func IterationsLTE(v int) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldIterations, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Report) predicate.Report {
	return predicate.Report(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Report) predicate.Report {
	return predicate.Report(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Report) predicate.Report {
	return predicate.Report(sql.NotPredicates(p))
}
