// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package logsclientmocks

import (
	"context"
	"time"

	"github.com/serengeti-sh/meerkat/internal/logsclient"
	mock "github.com/stretchr/testify/mock"
)

// NewClientMock creates a new instance of ClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientMock {
	mock := &ClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClientMock is an autogenerated mock type for the Client type
type ClientMock struct {
	mock.Mock
}

type ClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientMock) EXPECT() *ClientMock_Expecter {
	return &ClientMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type ClientMock
func (_mock *ClientMock) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ClientMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *ClientMock_Expecter) Close() *ClientMock_Close_Call {
	return &ClientMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *ClientMock_Close_Call) Run(run func()) *ClientMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClientMock_Close_Call) Return(err error) *ClientMock_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientMock_Close_Call) RunAndReturn(run func() error) *ClientMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetContext provides a mock function for the type ClientMock
func (_mock *ClientMock) GetContext(ctx context.Context, service string, start time.Time, end time.Time, limit int) ([]logsclient.SearchResult, error) {
	ret := _mock.Called(ctx, service, start, end, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 []logsclient.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, int) ([]logsclient.SearchResult, error)); ok {
		return returnFunc(ctx, service, start, end, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, int) []logsclient.SearchResult); ok {
		r0 = returnFunc(ctx, service, start, end, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]logsclient.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time, int) error); ok {
		r1 = returnFunc(ctx, service, start, end, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type ClientMock_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
//   - ctx context.Context
//   - service string
//   - start time.Time
//   - end time.Time
//   - limit int
func (_e *ClientMock_Expecter) GetContext(ctx interface{}, service interface{}, start interface{}, end interface{}, limit interface{}) *ClientMock_GetContext_Call {
	return &ClientMock_GetContext_Call{Call: _e.mock.On("GetContext", ctx, service, start, end, limit)}
}

func (_c *ClientMock_GetContext_Call) Run(run func(ctx context.Context, service string, start time.Time, end time.Time, limit int)) *ClientMock_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ClientMock_GetContext_Call) Return(searchResults []logsclient.SearchResult, err error) *ClientMock_GetContext_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *ClientMock_GetContext_Call) RunAndReturn(run func(ctx context.Context, service string, start time.Time, end time.Time, limit int) ([]logsclient.SearchResult, error)) *ClientMock_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// Ingest provides a mock function for the type ClientMock
func (_mock *ClientMock) Ingest(ctx context.Context, entries []logsclient.Entry) (*logsclient.IngestResult, error) {
	ret := _mock.Called(ctx, entries)

	if len(ret) == 0 {
		panic("no return value specified for Ingest")
	}

	var r0 *logsclient.IngestResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []logsclient.Entry) (*logsclient.IngestResult, error)); ok {
		return returnFunc(ctx, entries)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []logsclient.Entry) *logsclient.IngestResult); ok {
		r0 = returnFunc(ctx, entries)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*logsclient.IngestResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []logsclient.Entry) error); ok {
		r1 = returnFunc(ctx, entries)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_Ingest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ingest'
type ClientMock_Ingest_Call struct {
	*mock.Call
}

// Ingest is a helper method to define mock.On call
//   - ctx context.Context
//   - entries []logsclient.Entry
func (_e *ClientMock_Expecter) Ingest(ctx interface{}, entries interface{}) *ClientMock_Ingest_Call {
	return &ClientMock_Ingest_Call{Call: _e.mock.On("Ingest", ctx, entries)}
}

func (_c *ClientMock_Ingest_Call) Run(run func(ctx context.Context, entries []logsclient.Entry)) *ClientMock_Ingest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []logsclient.Entry
		if args[1] != nil {
			arg1 = args[1].([]logsclient.Entry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientMock_Ingest_Call) Return(ingestResult *logsclient.IngestResult, err error) *ClientMock_Ingest_Call {
	_c.Call.Return(ingestResult, err)
	return _c
}

func (_c *ClientMock_Ingest_Call) RunAndReturn(run func(ctx context.Context, entries []logsclient.Entry) (*logsclient.IngestResult, error)) *ClientMock_Ingest_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type ClientMock
func (_mock *ClientMock) Search(ctx context.Context, query string, opts logsclient.SearchOptions) ([]logsclient.SearchResult, error) {
	ret := _mock.Called(ctx, query, opts)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []logsclient.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, logsclient.SearchOptions) ([]logsclient.SearchResult, error)); ok {
		return returnFunc(ctx, query, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, logsclient.SearchOptions) []logsclient.SearchResult); ok {
		r0 = returnFunc(ctx, query, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]logsclient.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, logsclient.SearchOptions) error); ok {
		r1 = returnFunc(ctx, query, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type ClientMock_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - opts logsclient.SearchOptions
func (_e *ClientMock_Expecter) Search(ctx interface{}, query interface{}, opts interface{}) *ClientMock_Search_Call {
	return &ClientMock_Search_Call{Call: _e.mock.On("Search", ctx, query, opts)}
}

func (_c *ClientMock_Search_Call) Run(run func(ctx context.Context, query string, opts logsclient.SearchOptions)) *ClientMock_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 logsclient.SearchOptions
		if args[2] != nil {
			arg2 = args[2].(logsclient.SearchOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ClientMock_Search_Call) Return(searchResults []logsclient.SearchResult, err error) *ClientMock_Search_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *ClientMock_Search_Call) RunAndReturn(run func(ctx context.Context, query string, opts logsclient.SearchOptions) ([]logsclient.SearchResult, error)) *ClientMock_Search_Call {
	_c.Call.Return(run)
	return _c
}
