// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package collectormocks

import (
	"github.com/serengeti-sh/meerkat/internal/collector"
	mock "github.com/stretchr/testify/mock"
)

// NewLogAdderMock creates a new instance of LogAdderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogAdderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogAdderMock {
	mock := &LogAdderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LogAdderMock is an autogenerated mock type for the LogAdder type
type LogAdderMock struct {
	mock.Mock
}

type LogAdderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LogAdderMock) EXPECT() *LogAdderMock_Expecter {
	return &LogAdderMock_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type LogAdderMock
func (_mock *LogAdderMock) Add(entry collector.LogEntry) {
	_mock.Called(entry)
	return
}

// LogAdderMock_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type LogAdderMock_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - entry collector.LogEntry
func (_e *LogAdderMock_Expecter) Add(entry interface{}) *LogAdderMock_Add_Call {
	return &LogAdderMock_Add_Call{Call: _e.mock.On("Add", entry)}
}

func (_c *LogAdderMock_Add_Call) Run(run func(entry collector.LogEntry)) *LogAdderMock_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 collector.LogEntry
		if args[0] != nil {
			arg0 = args[0].(collector.LogEntry)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *LogAdderMock_Add_Call) Return() *LogAdderMock_Add_Call {
	_c.Call.Return()
	return _c
}

func (_c *LogAdderMock_Add_Call) RunAndReturn(run func(entry collector.LogEntry)) *LogAdderMock_Add_Call {
	_c.Run(run)
	return _c
}
