// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package analyzerMocks

import (
	"context"
	"encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// NewToolMock creates a new instance of ToolMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewToolMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ToolMock {
	mock := &ToolMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ToolMock is an autogenerated mock type for the Tool type
type ToolMock struct {
	mock.Mock
}

type ToolMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ToolMock) EXPECT() *ToolMock_Expecter {
	return &ToolMock_Expecter{mock: &_m.Mock}
}

// Description provides a mock function for the type ToolMock
func (_mock *ToolMock) Description() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ToolMock_Description_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Description'
type ToolMock_Description_Call struct {
	*mock.Call
}

// Description is a helper method to define mock.On call
func (_e *ToolMock_Expecter) Description() *ToolMock_Description_Call {
	return &ToolMock_Description_Call{Call: _e.mock.On("Description")}
}

func (_c *ToolMock_Description_Call) Run(run func()) *ToolMock_Description_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolMock_Description_Call) Return(s string) *ToolMock_Description_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ToolMock_Description_Call) RunAndReturn(run func() string) *ToolMock_Description_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function for the type ToolMock
func (_mock *ToolMock) Execute(ctx context.Context, args json.RawMessage) (string, error) {
	ret := _mock.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, json.RawMessage) (string, error)); ok {
		return returnFunc(ctx, args)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, json.RawMessage) string); ok {
		r0 = returnFunc(ctx, args)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, json.RawMessage) error); ok {
		r1 = returnFunc(ctx, args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ToolMock_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ToolMock_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - args json.RawMessage
func (_e *ToolMock_Expecter) Execute(ctx interface{}, args interface{}) *ToolMock_Execute_Call {
	return &ToolMock_Execute_Call{Call: _e.mock.On("Execute", ctx, args)}
}

func (_c *ToolMock_Execute_Call) Run(run func(ctx context.Context, args json.RawMessage)) *ToolMock_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 json.RawMessage
		if args[1] != nil {
			arg1 = args[1].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ToolMock_Execute_Call) Return(s string, err error) *ToolMock_Execute_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *ToolMock_Execute_Call) RunAndReturn(run func(ctx context.Context, args json.RawMessage) (string, error)) *ToolMock_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type ToolMock
func (_mock *ToolMock) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ToolMock_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type ToolMock_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *ToolMock_Expecter) Name() *ToolMock_Name_Call {
	return &ToolMock_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *ToolMock_Name_Call) Run(run func()) *ToolMock_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolMock_Name_Call) Return(s string) *ToolMock_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ToolMock_Name_Call) RunAndReturn(run func() string) *ToolMock_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Parameters provides a mock function for the type ToolMock
func (_mock *ToolMock) Parameters() json.RawMessage {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Parameters")
	}

	var r0 json.RawMessage
	if returnFunc, ok := ret.Get(0).(func() json.RawMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	return r0
}

// ToolMock_Parameters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parameters'
type ToolMock_Parameters_Call struct {
	*mock.Call
}

// Parameters is a helper method to define mock.On call
func (_e *ToolMock_Expecter) Parameters() *ToolMock_Parameters_Call {
	return &ToolMock_Parameters_Call{Call: _e.mock.On("Parameters")}
}

func (_c *ToolMock_Parameters_Call) Run(run func()) *ToolMock_Parameters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolMock_Parameters_Call) Return(rawMessage json.RawMessage) *ToolMock_Parameters_Call {
	_c.Call.Return(rawMessage)
	return _c
}

func (_c *ToolMock_Parameters_Call) RunAndReturn(run func() json.RawMessage) *ToolMock_Parameters_Call {
	_c.Call.Return(run)
	return _c
}
