// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// InspectRule is the predicate function for inspectrule builders.
type InspectRule func(*sql.Selector)

// Report is the predicate function for report builders.
type Report func(*sql.Selector)
